In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("grades.csv")

In [3]:
df

                                            submission        submit_time
0    https://ckd.upgrad.com/UpGrad/73ba5189-94fd-44...  01/03/17-20:28:52
1    https://ckd.upgrad.com/UpGrad/185242ff-7508-4c...  01/03/17-20:18:21
2    https://ckd.upgrad.com/UpGrad/a353d129-c100-43...  01/03/17-22:37:08
3    https://ckd.upgrad.com/UpGrad/002fc912-faa1-49...  01/02/17-21:43:19
4    https://ckd.upgrad.com/UpGrad/25cbc4a4-6d49-4f...  01/03/17-15:27:49
..                                                 ...                ...
193  https://ckd.upgrad.com/UpGrad/ba485323-bba6-4b...  01/03/17-22:43:12
194  https://ckd.upgrad.com/UpGrad/a65694d0-339b-44...  01/09/17-23:59:34
195  https://ckd.upgrad.com/UpGrad/c3876ddf-2b2f-4a...  12/19/16-21:44:13
196  https://ckd.upgrad.com/UpGrad/2b9732ad-0985-4a...  01/09/17-23:23:06
197  https://ckd.upgrad.com/UpGrad/21da378c-75a4-4a...  01/03/17-22:32:38

[198 rows x 2 columns]

In [6]:
df["submission"]

0      https://ckd.upgrad.com/UpGrad/73ba5189-94fd-44...
1      https://ckd.upgrad.com/UpGrad/185242ff-7508-4c...
2      https://ckd.upgrad.com/UpGrad/a353d129-c100-43...
3      https://ckd.upgrad.com/UpGrad/002fc912-faa1-49...
4      https://ckd.upgrad.com/UpGrad/25cbc4a4-6d49-4f...
                             ...
193    https://ckd.upgrad.com/UpGrad/ba485323-bba6-4b...
194    https://ckd.upgrad.com/UpGrad/a65694d0-339b-44...
195    https://ckd.upgrad.com/UpGrad/c3876ddf-2b2f-4a...
196    https://ckd.upgrad.com/UpGrad/2b9732ad-0985-4a...
197    https://ckd.upgrad.com/UpGrad/21da378c-75a4-4a...
Name: submission, Length: 198, dtype: object

In [5]:
df.head(30)

                                           submission        submit_time
0   https://ckd.upgrad.com/UpGrad/73ba5189-94fd-44...  01/03/17-20:28:52
1   https://ckd.upgrad.com/UpGrad/185242ff-7508-4c...  01/03/17-20:18:21
2   https://ckd.upgrad.com/UpGrad/a353d129-c100-43...  01/03/17-22:37:08
3   https://ckd.upgrad.com/UpGrad/002fc912-faa1-49...  01/02/17-21:43:19
4   https://ckd.upgrad.com/UpGrad/25cbc4a4-6d49-4f...  01/03/17-15:27:49
5   https://ckd.upgrad.com/UpGrad/0ab308ab-2b3a-4c...  01/04/17-02:43:46
6   https://ckd.upgrad.com/UpGrad/ba2c249c-dac8-46...  01/03/17-23:41:25
7   https://ckd.upgrad.com/UpGrad/d8969806-6760-44...  01/09/17-23:49:09
8   https://ckd.upgrad.com/UpGrad/5ff1d0ab-816b-48...  12/30/16-14:14:17
9   https://ckd.upgrad.com/UpGrad/0d507851-d102-47...  01/03/17-21:18:04
10  https://ckd.upgrad.com/UpGrad/9a756d83-7a83-49...  01/03/17-23:55:41
11  https://ckd.upgrad.com/UpGrad/873211b9-5a3q-45...  01/09/17-23:41:23
12  https://ckd.upgrad.com/UpGrad/1c4b7a1a-8287-45...  01/03/17-23:49:21
13  https://ckd.upgrad.com/UpGrad/7091a8b2-d3ba-43...  01/03/17-20:13:50
14  https://ckd.upgrad.com/UpGrad/5adfdcbb-a728-49...  01/03/17-20:52:33
15  https://ckd.upgrad.com/UpGrad/042f9a24-6595-44...  01/03/17-18:22:59
16  https://ckd.upgrad.com/UpGrad/f0c04fba-56d2-4a...  01/04/17-01:43:43
17  https://ckd.upgrad.com/UpGrad/bb7a7237-419d-40...  01/03/17-23:59:35
18  https://ckd.upgrad.com/UpGrad/a790dc52-359f-47...  01/02/17-23:45:18
19  https://ckd.upgrad.com/UpGrad/420af317-8a55-4a...  01/03/17-23:20:31
20  https://ckd.upgrad.com/UpGrad/8268791a-c6a8-42...  01/03/17-23:56:45
21  https://ckd.upgrad.com/UpGrad/7cbc35aa-1d5c-4d...  01/09/17-23:59:21
22  https://ckd.upgrad.com/UpGrad/1244015f-95d6-45...  01/03/17-14:52:54
23  https://ckd.upgrad.com/UpGrad/a65db4a2-3d36-46...  01/01/17-22:03:32
24  https://ckd.upgrad.com/UpGrad/a4d13ca3-9b40-40...  01/04/17-00:04:08
25  https://ckd.upgrad.com/UpGrad/7996d076-6118-48...  01/03/17-20:40:53
26  https://ckd.upgrad.com/UpGrad/8fd2afb9-7bc2-41...  01/03/17-23:11:11
27  https://ckd.upgrad.com/UpGrad/a19279d5-a025-45...  01/03/17-21:36:16
28  https://ckd.upgrad.com/UpGrad/3f50884a-4fd0-48...  01/09/17-23:26:15
29  https://ckd.upgrad.com/UpGrad/48781790-093d-42...  01/04/17-00:03:26

In [7]:
#You can use the “str_count()” function(This function is present in R language) from the string library, which would return 1 if the submission columns contain “.zip” text.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 198 entries, 0 to 197
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   submission   198 non-null    object
 1   submit_time  198 non-null    object
dtypes: object(2)
memory usage: 3.2+ KB

In [10]:
df.head(2)

                                          submission        submit_time
0  https://ckd.upgrad.com/UpGrad/73ba5189-94fd-44...  01/03/17-20:28:52
1  https://ckd.upgrad.com/UpGrad/185242ff-7508-4c...  01/03/17-20:18:21

In [12]:
df['submit_time'] = pd.to_datetime(df['submit_time'], format='%m/%d/%y-%H:%M:%S')

In [14]:
df['date'] = df['submit_time'].dt.date
df['day'] = df['submit_time'].dt.day
df['month'] = df['submit_time'].dt.month
df['year'] = df['submit_time'].dt.year
df['hour'] = df['submit_time'].dt.hour
df['minute'] = df['submit_time'].dt.minute

In [20]:
df.to_csv("newgrade.csv")

In [23]:
df

,submission,submit_time,date,day,month,year,hour,minute
0,https://ckd.upgrad.com/UpGrad/73ba5189-94fd-44...,2017-01-03 20:28:52,2017-01-03,3,1,2017,20,28
1,https://ckd.upgrad.com/UpGrad/185242ff-7508-4c...,2017-01-03 20:18:21,2017-01-03,3,1,2017,20,18
2,https://ckd.upgrad.com/UpGrad/a353d129-c100-43...,2017-01-03 22:37:08,2017-01-03,3,1,2017,22,37
3,https://ckd.upgrad.com/UpGrad/002fc912-faa1-49...,2017-01-02 21:43:19,2017-01-02,2,1,2017,21,43
4,https://ckd.upgrad.com/UpGrad/25cbc4a4-6d49-4f...,2017-01-03 15:27:49,2017-01-03,3,1,2017,15,27
...,...,...,...,...,...,...,...,...
193,https://ckd.upgrad.com/UpGrad/ba485323-bba6-4b...,2017-01-03 22:43:12,2017-01-03,3,1,2017,22,43
194,https://ckd.upgrad.com/UpGrad/a65694d0-339b-44...,2017-01-09 23:59:34,2017-01-09,9,1,2017,23,59
195,https://ckd.upgrad.com/UpGrad/c3876ddf-2b2f-4a...,2016-12-19 21:44:13,2016-12-19,19,12,2016,21,44
196,https://ckd.upgrad.com/UpGrad/2b9732ad-0985-4a...,2017-01-09 23:23:06,2017-01-09,9,1,2017,23,23
197,https://ckd.upgrad.com/UpGrad/21da378c-75a4-4a...,2017-01-03 22:32:38,2017-01-03,3,1,2017,22,32

In [24]:
df["hour"].value_counts()

hour
23    66
21    27
22    24
20    16
0     10
1      8
14     6
18     6
13     6
15     4
17     4
12     3
10     3
3      3
19     2
4      2
16     2
2      2
6      1
8      1
11     1
9      1
Name: count, dtype: int64