In [1]:
## Pandas ---> Python Data Analysis library
#pandas -----> Used to handle Datasets in the form of dataframes (originally in the form of excel or csv etc)

In [77]:
#How to import Pandas
import pandas as pd

In [78]:
#Load The Data
#file name
df=pd.read_csv("day.csv")
#filepath Windows
#df.read_csv(r"C:/Downloads/day.csv")
#file Path Mac right click option 
df

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,01-01-2018,1,0,1,0,1,1,2,14.110847,18.181250,80.5833,10.749882,331,654,985
1,2,02-01-2018,1,0,1,0,2,1,2,14.902598,17.686950,69.6087,16.652113,131,670,801
2,3,03-01-2018,1,0,1,0,3,1,1,8.050924,9.470250,43.7273,16.636703,120,1229,1349
3,4,04-01-2018,1,0,1,0,4,1,1,8.200000,10.606100,59.0435,10.739832,108,1454,1562
4,5,05-01-2018,1,0,1,0,5,1,1,9.305237,11.463500,43.6957,12.522300,82,1518,1600
5,6,06-01-2018,1,0,1,0,6,0,1,8.378268,11.660450,51.8261,6.000868,88,1518,1606
6,7,07-01-2018,1,0,1,0,0,0,2,8.057402,10.441950,49.8696,11.304642,148,1362,1510
7,8,08-01-2018,1,0,1,0,1,1,2,6.765000,8.112700,53.5833,17.875868,68,891,959
8,9,09-01-2018,1,0,1,0,2,1,1,5.671653,5.808750,43.4167,24.250650,54,768,822
9,10,10-01-2018,1,0,1,0,3,1,1,6.184153,7.544400,48.2917,14.958889,41,1280,1321
10,11,11-01-2018,1,0,1,0,4,1,2,6.932731,9.573200,68.6364,8.182844,43,1220,1263
11,12,12-01-2018,1,0,1,0,5,1,1,7.081807,8.023650,59.9545,20.410009,25,1137,1162
12,13,13-01-2018,1,0,1,0,6,0,1,6.765000,7.544150,47.0417,20.167000,38,1368,1406
13,14,14-01-2018,1,0,1,0,0,0,1,6.595670,9.420650,53.7826,8.478716,54,1367,1421
14,15,15-01-2018,1,0,1,0,1,1,2,9.566653,12.405600,49.8750,10.583521,222,1026,1248
15,16,16-01-2018,1,0,1,0,2,1,1,9.498347,11.710850,48.3750,12.625011,251,953,1204
16,17,17-01-2018,1,0,1,1,3,0,2,7.209153,8.838550,53.7500,12.999139,117,883,1000
17,18,18-01-2018,1,0,1,0,4,1,2,8.883347,11.616650,86.1667,9.833925,9,674,683
18,19,19-01-2018,1,0,1,0,5,1,2,11.979134,14.921100,74.1739,13.957239,78,1572,1650
19,20,20-01-2018,1,0,1,0,6,0,2,10.728347,12.752500,53.8333,13.125568,83,1844,1927
20,21,21-01-2018,1,0,1,0,0,0,1,7.277500,7.891650,45.7083,23.667214,75,1468,1543
21,22,22-01-2018,1,0,1,0,1,1,1,2.424346,3.953480,40.0000,11.521990,93,888,981
22,23,23-01-2018,1,0,1,0,2,1,1,3.957390,4.941955,43.6522,16.522200,150,836,986
23,24,24-01-2018,1,0,1,0,3,1,1,3.993043,5.896500,49.1739,10.608110,86,1330,1416
24,25,25-01-2018,1,0,1,0,4,1,2,9.162598,11.726300,61.6957,8.696332,186,1799,1985
25,26,26-01-2018,1,0,1,0,5,1,3,8.917500,10.180000,86.2500,19.687950,34,472,506
26,27,27-01-2018,1,0,1,0,6,0,1,7.995000,10.985000,68.7500,7.627079,15,416,431
27,28,28-01-2018,1,0,1,0,0,0,2,8.342598,11.165850,79.3043,8.261100,38,1129,1167
28,29,29-01-2018,1,0,1,0,1,1,1,8.057402,10.606300,65.1739,9.739455,123,975,1098
29,30,30-01-2018,1,0,1,0,2,1,1,8.877402,12.516100,72.2174,4.956834,140,956,1096
30,31,31-01-2018,1,0,1,0,3,1,2,7.414153,9.312500,60.3750,12.541864,42,1459,1501
31,32,01-02-2018,1,0,2,0,4,1,2,7.879134,11.726500,82.9565,3.565271,47,1313,1360
32,33,02-02-2018,1,0,2,0,5,1,2,10.660000,12.720850,77.5417,17.708636,72,1454,1526
33,34,03-02-2018,1,0,2,0,6,0,1,7.665237,8.893900,43.7826,18.609384,61,1489,1550
34,35,04-02-2018,1,0,2,0,0,0,2,8.663464,11.429350,58.5217,8.565213,88,1620,1708
35,36,05-02-2018,1,0,2,0,1,1,2,9.566653,12.152900,92.9167,10.792293,100,905,1005
36,37,06-02-2018,1,0,2,0,2,1,1,11.719153,14.583550,56.8333,9.500600,354,1269,1623
37,38,07-02-2018,1,0,2,0,3,1,1,11.138347,15.182900,73.8333,3.042356,120,1592,1712
38,39,08-02-2018,1,0,2,0,4,1,1,9.054153,9.912300,53.7917,24.250650,64,1466,1530
39,40,09-02-2018,1,0,2,0,5,1,2,5.526103,7.214150,49.4783,12.652213,53,1552,1605
40,41,10-02-2018,1,0,2,0,6,0,1,5.918268,7.477400,43.7391,14.869645,47,1491,1538
41,42,11-02-2018,1,0,2,0,0,0,1,7.752731,10.675450,50.6364,7.272850,149,1597,1746
42,43,12-02-2018,1,0,2,0,1,1,1,9.122500,11.647700,54.4167,13.625589,288,1184,1472
43,44,13-02-2018,1,0,2,0,2,1,1,12.977402,16.205650,45.7391,17.479161,397,1192,1589
44,45,14-02-2018,1,0,2,0,3,1,1,17.015000,19.917500,37.5833,27.999836,208,1705,1913
45,46,15-02-2018,1,0,2,0,4,1,1,10.909567,12.713700,31.4348,19.522058,140,1675,1815
46,47,16-02-2018,1,0,2,0,5,1,1,13.048701,15.810000,42.3478,16.869997,218,1897,2115
47,48,17-02-2018,1,0,2,0,6,0,1,17.869153,21.432900,50.5000,15.416968,259,2216,2475
48,49,18-02-2018,1,0,2,0,0,0,1,21.388347,25.599150,51.6667,17.749975,579,2348,2927
49,50,19-02-2018,1,0,2,0,1,1,1,16.365847,19.570200,18.7917,34.000021,532,1103,1635
50,51,20-02-2018,1,0,2,0,2,1,1,11.693897,13.866500,40.7826,14.956745,639,1173,1812
51,52,21-02-2018,1,0,2,1,3,0,2,12.436653,14.203750,60.5000,20.625682,195,912,1107
52,53,22-02-2018,1,0,2,0,4,1,1,7.471102,9.301650,57.7778,13.110761,74,1376,1450
53,54,23-02-2018,1,0,2,0,5,1,1,9.091299,12.285850,42.3043,6.305571,139,1778,1917
54,55,24-02-2018,1,0,2,0,6,0,2,12.121732,14.459550,69.7391,16.783232,100,1707,1807
55,56,25-02-2018,1,0,2,0,0,0,2,14.938268,17.523050,71.2174,23.218113,120,1341,1461
56,57,26-02-2018,1,0,2,0,1,1,1,11.582500,14.109600,53.7917,12.500257,424,1545,1969
57,58,27-02-2018,1,0,2,0,2,1,1,14.082598,17.555450,68.0000,8.391616,694,1708,2402
58,59,28-02-2018,1,0,2,0,3,1,2,16.698193,20.005900,87.6364,19.408962,81,1365,1446
59,60,01-03-2018,1,0,3,0,4,1,1,10.933347,13.193950,53.5000,14.500475,137,1714,1851
60,61,02-03-2018,1,0,3,0,5,1,1,13.735000,16.003550,44.9583,20.624811,231,1903,2134
61,62,03-03-2018,1,0,3,0,6,0,1,8.131653,10.006650,31.8333,15.125518,123,1562,1685
62,63,04-03-2018,1,0,3,0,0,0,2,10.728347,12.783950,61.0417,13.624182,214,1730,1944
63,64,05-03-2018,1,0,3,0,1,1,2,15.750847,18.938950,78.9167,16.875357,640,1437,2077
64,65,06-03-2018,1,0,3,0,2,1,2,15.437402,18.312600,94.8261,23.000229,114,491,605
65,66,07-03-2018,1,0,3,0,3,1,1,10.731299,11.923050,55.1304,22.870584,244,1628,1872
66,67,08-03-2018,1,0,3,0,4,1,1,11.992500,15.120000,42.0833,8.083550,316,1817,2133
67,68,09-03-2018,1,0,3,0,5,1,2,12.129153,14.330400,77.5417,14.750050,191,1700,1891
68,69,10-03-2018,1,0,3,0,6,0,3,15.952731,19.283400,0.0000,17.545759,46,577,623
69,70,11-03-2018,1,0,3,0,0,0,2,12.977402,15.250000,64.9565,15.608990,247,1730,1977
70,71,12-03-2018,1,0,3,0,1,1,1,13.495847,16.287500,59.4583,14.791925,724,1408,2132
71,72,13-03-2018,1,0,3,0,2,1,1,15.758268,19.004550,52.7391,18.130468,982,1435,2417
72,73,14-03-2018,1,0,3,0,3,1,1,13.333897,16.600000,49.6957,9.174042,359,1687,2046
73,74,15-03-2018,1,0,3,0,4,1,2,13.013031,15.908900,65.5652,12.348703,289,1767,2056
74,75,16-03-2018,1,0,3,0,5,1,2,14.973897,18.346500,77.6522,13.608839,321,1871,2192
75,76,17-03-2018,1,0,3,0,6,0,1,17.015000,20.516650,60.2917,14.041793,424,2320,2744
76,77,18-03-2018,1,0,3,0,0,0,1,22.140000,26.350450,52.5217,15.478139,884,2355,3239
77,78,19-03-2018,1,0,3,0,1,1,1,19.372500,23.326250,37.9167,24.667189,1424,1693,3117
78,79,20-03-2018,1,0,3,0,2,1,1,13.632500,16.287500,47.3750,13.917307,1047,1424,2471
79,80,21-03-2018,2,0,3,0,3,1,2,17.647835,20.486750,73.7391,19.348461,401,1676,2077
80,81,22-03-2018,2,0,3,0,4,1,1,18.108347,22.032100,62.4583,15.125250,460,2243,2703
81,82,23-03-2018,2,0,3,0,5,1,2,14.225237,16.896950,83.9565,15.695487,203,1918,2121
82,83,24-03-2018,2,0,3,0,6,0,2,11.685000,13.541650,80.5833,16.333729,166,1699,1865
83,84,25-03-2018,2,0,3,0,0,0,1,10.830847,12.815600,49.5000,15.458575,300,1910,2210
84,85,26-03-2018,2,0,3,0,1,1,1,10.899153,12.878550,39.4167,14.041257,981,1515,2496
85,86,27-03-2018,2,0,3,0,2,1,2,10.374763,12.516950,49.3913,12.348100,472,1221,1693
86,87,28-03-2018,2,0,3,0,3,1,1,10.838268,12.878700,30.2174,14.217668,222,1806,2028
87,88,29-03-2018,2,0,3,0,4,1,1,12.402500,14.645400,31.4167,15.208732,317,2108,2425
88,89,30-03-2018,2,0,3,0,5,1,2,12.300000,14.867500,64.6667,11.583496,168,1368,1536
89,90,31-03-2018,2,0,3,0,6,0,3,11.001653,12.878750,91.8333,14.582282,179,1506,1685
90,91,01-04-2018,2,0,4,0,0,0,2,12.300000,14.172700,68.6250,17.333436,307,1920,2227
91,92,02-04-2018,2,0,4,0,1,1,2,12.915000,15.781850,65.3750,13.208782,898,1354,2252
92,93,03-04-2018,2,0,4,0,2,1,1,15.511653,18.938350,48.0000,12.208271,1651,1598,3249
93,94,04-04-2018,2,0,4,0,3,1,1,23.506653,27.146450,42.6250,25.833257,734,2381,3115
94,95,05-04-2018,2,0,4,0,4,1,2,16.980847,19.917500,64.2083,26.000489,167,1628,1795
95,96,06-04-2018,2,0,4,0,5,1,1,16.024153,19.380400,47.0833,17.625221,413,2395,2808
96,97,07-04-2018,2,0,4,0,6,0,1,17.937500,21.684800,60.2917,10.874904,571,2570,3141
97,98,08-04-2018,2,0,4,0,0,0,2,13.769153,16.223950,83.6250,15.208464,172,1299,1471
98,99,09-04-2018,2,0,4,0,1,1,2,14.042500,17.076450,87.7500,8.916561,879,1576,2455
99,100,10-04-2018,2,0,4,0,2,1,2,17.493347,21.336850,85.7500,9.833389,1188,1707,2895
100,101,11-04-2018,2,0,4,0,3,1,2,24.421732,28.260850,71.6956,21.739758,855,2493,3348
101,102,12-04-2018,2,0,4,0,4,1,2,20.602500,24.652700,73.9167,18.416893,257,1777,2034
102,103,13-04-2018,2,0,4,0,5,1,2,16.912500,20.864150,81.9167,16.791339,209,1953,2162
103,104,14-04-2018,2,0,4,0,6,0,1,19.167500,23.137100,54.0417,7.416900,529,2738,3267
104,105,15-04-2018,2,0,4,1,0,0,1,18.313347,22.095650,67.1250,15.167125,642,2484,3126
105,106,16-04-2018,2,0,4,0,1,1,3,17.664153,21.274600,88.8333,22.834136,121,674,795
106,107,17-04-2018,2,0,4,0,2,1,1,18.723347,22.284800,47.9583,20.334232,1558,2186,3744
107,108,18-04-2018,2,0,4,0,3,1,1,21.012500,25.157300,54.2500,10.958989,669,2760,3429
108,109,19-04-2018,2,0,4,0,4,1,2,20.739153,24.462900,66.5833,10.584057,409,2795,3204
109,110,20-04-2018,2,0,4,0,5,1,1,24.395000,28.219600,61.4167,16.208975,613,3331,3944
110,111,21-04-2018,2,0,4,0,6,0,1,18.825847,22.694600,40.7083,21.792286,745,3444,4189
111,112,22-04-2018,2,0,4,0,0,0,2,13.803347,16.097700,72.9583,14.707907,177,1506,1683
112,113,23-04-2018,2,0,4,0,1,1,2,18.860000,22.506050,88.7917,15.458575,1462,2574,4036
113,114,24-04-2018,2,0,4,0,2,1,2,23.848347,27.588150,81.0833,12.875725,1710,2481,4191
114,115,25-04-2018,2,0,4,0,3,1,1,24.873347,28.725000,77.6667,12.417311,773,3300,4073
115,116,26-04-2018,2,0,4,0,4,1,1,25.898347,29.704150,72.9167,21.875500,678,3722,4400
116,117,27-04-2018,2,0,4,0,5,1,2,25.420000,28.757100,83.5417,20.917400,547,3325,3872
117,118,28-04-2018,2,0,4,0,6,0,2,25.317500,28.946450,70.0833,21.500836,569,3489,4058
118,119,29-04-2018,2,0,4,0,0,0,1,20.910000,24.873150,45.7083,16.084221,878,3717,4595
119,120,30-04-2018,2,0,4,0,1,1,1,19.372500,23.201050,50.3333,15.750025,1965,3347,5312
120,121,01-05-2018,2,0,5,0,2,1,2,18.518347,22.410200,76.2083,7.125718,1138,2213,3351
121,122,02-05-2018,2,0,5,0,3,1,2,22.515847,26.641650,73.0000,12.291418,847,3554,4401
122,123,03-05-2018,2,0,5,0,4,1,2,25.283347,29.103950,69.7083,22.958689,603,3848,4451
123,124,04-05-2018,2,0,5,0,5,1,2,16.980847,20.232500,73.7083,22.042732,255,2378,2633
124,125,05-05-2018,2,0,5,0,6,0,1,18.825847,22.095850,44.4167,19.791264,614,3819,4433
125,126,06-05-2018,2,0,5,0,0,0,1,19.645847,23.705850,59.0000,15.292482,894,3714,4608
126,127,07-05-2018,2,0,5,0,1,1,1,21.320000,25.631050,54.1250,10.750150,1612,3102,4714
127,128,08-05-2018,2,0,5,0,2,1,1,21.661653,25.946650,63.1667,5.000712,1401,2932,4333
128,129,09-05-2018,2,0,5,0,3,1,1,21.832500,26.262300,58.8750,11.792000,664,3698,4362
129,130,10-05-2018,2,0,5,0,4,1,1,21.832500,26.136050,48.9167,7.749957,694,4109,4803
130,131,11-05-2018,2,0,5,0,5,1,1,22.242500,26.420000,63.2917,8.083014,550,3632,4182
131,132,12-05-2018,2,0,5,0,6,0,1,21.935000,26.168150,74.7500,12.707689,695,4169,4864
132,133,13-05-2018,2,0,5,0,0,0,2,21.012500,24.715000,86.3333,12.041575,692,3413,4105
133,134,14-05-2018,2,0,5,0,1,1,2,21.354153,25.031450,92.2500,9.041650,902,2507,3409
134,135,15-05-2018,2,0,5,0,2,1,2,23.062500,26.800000,86.7083,10.249593,1582,2971,4553
135,136,16-05-2018,2,0,5,0,3,1,1,23.677500,27.525600,78.7917,8.500357,773,3185,3958
136,137,17-05-2018,2,0,5,0,4,1,2,23.028347,26.926450,83.7917,18.582718,678,3445,4123
137,138,18-05-2018,2,0,5,0,5,1,2,22.550000,26.357900,87.0000,13.499964,536,3319,3855
138,139,19-05-2018,2,0,5,0,6,0,2,21.764153,25.537100,82.9583,7.250271,735,3840,4575
139,140,20-05-2018,2,0,5,0,0,0,1,22.003347,26.452100,71.9583,8.375871,909,4008,4917
140,141,21-05-2018,2,0,5,0,1,1,1,24.702500,28.598750,62.6667,8.083550,2258,3547,5805
141,142,22-05-2018,2,0,5,0,2,1,1,24.770847,28.725000,74.9583,9.916536,1576,3084,4660
142,143,23-05-2018,2,0,5,0,3,1,2,25.898347,29.514800,81.0000,15.667414,836,3438,4274
143,144,24-05-2018,2,0,5,0,4,1,2,27.060000,30.240650,74.0833,13.875164,659,3833,4492
144,145,25-05-2018,2,0,5,0,5,1,1,27.094153,30.777100,69.6250,10.333611,740,4238,4978
145,146,26-05-2018,2,0,5,0,6,0,1,29.041653,32.734400,67.7500,13.376014,758,3919,4677
146,147,27-05-2018,2,0,5,0,0,0,1,27.948347,31.850400,65.3750,16.125493,871,3808,4679
147,148,28-05-2018,2,0,5,0,1,1,1,26.889153,30.618950,72.9583,15.416164,2001,2757,4758
148,149,29-05-2018,2,0,5,0,2,1,1,27.367500,30.777500,81.8750,14.333846,2355,2433,4788
149,150,30-05-2018,2,0,5,1,3,0,1,30.066653,33.554600,68.5000,8.792075,1549,2549,4098
150,151,31-05-2018,2,0,5,0,4,1,1,31.775000,36.269150,63.6667,7.459043,673,3309,3982
151,152,01-06-2018,2,0,6,0,5,1,2,31.330847,36.048350,67.7083,13.875164,513,3461,3974
152,153,02-06-2018,2,0,6,0,6,0,1,29.315000,32.197100,30.5000,19.583229,736,4232,4968
153,154,03-06-2018,2,0,6,0,0,0,1,25.420000,29.356650,35.4167,16.959107,898,4414,5312
154,155,04-06-2018,2,0,6,0,1,1,1,26.035000,29.734800,45.6250,8.250514,1869,3473,5342
155,156,05-06-2018,2,0,6,0,2,1,2,26.581653,30.840200,65.2500,9.292364,1685,3221,4906
156,157,06-06-2018,2,0,6,0,3,1,1,27.811653,31.092900,60.0000,8.167032,673,3875,4548
157,158,07-06-2018,2,0,6,0,4,1,1,29.007500,32.797500,59.7917,12.583136,763,4070,4833
158,159,08-06-2018,2,0,6,0,5,1,1,31.809153,36.363950,62.2083,9.166739,676,3725,4401
159,160,09-06-2018,2,0,6,0,6,0,2,33.141653,37.878950,56.8333,10.042161,563,3352,3915
160,161,10-06-2018,2,0,6,0,0,0,1,30.955000,35.164600,60.5000,9.417118,815,3771,4586
161,162,11-06-2018,2,0,6,0,1,1,1,29.725000,33.901900,65.4583,10.374950,1729,3237,4966
162,163,12-06-2018,2,0,6,0,2,1,1,28.392500,32.166250,74.7917,10.958989,1467,2993,4460
163,164,13-06-2018,2,0,6,0,3,1,1,26.035000,30.082700,49.4583,20.458450,863,4157,5020
164,165,14-06-2018,2,0,6,0,4,1,1,24.770847,29.577300,50.7083,18.041961,727,4164,4891
165,166,15-06-2018,2,0,6,0,5,1,1,25.693347,29.387700,47.1667,11.250104,769,4411,5180
166,167,16-06-2018,2,0,6,0,6,0,2,25.761653,29.767300,68.8333,13.833557,545,3222,3767
167,168,17-06-2018,2,0,6,0,0,0,1,26.615847,30.019150,73.5833,9.582943,863,3981,4844
168,169,18-06-2018,2,0,6,0,1,1,1,28.563347,32.197700,67.0417,8.000336,1807,3312,5119
169,170,19-06-2018,2,0,6,0,2,1,2,28.665847,32.292300,66.6667,6.834000,1639,3105,4744
170,171,20-06-2018,2,0,6,0,3,1,2,26.035000,29.767300,74.6250,10.416825,699,3311,4010
171,172,21-06-2018,3,0,6,0,4,1,2,27.914153,31.882300,77.0417,11.458675,774,4061,4835
172,173,22-06-2018,3,0,6,0,5,1,1,30.066653,34.691450,70.7500,11.541554,661,3846,4507
173,174,23-06-2018,3,0,6,0,6,0,2,29.861653,34.691650,70.3333,15.999868,746,4044,4790
174,175,24-06-2018,3,0,6,0,0,0,1,29.690847,32.829150,57.3333,14.875675,969,4022,4991
175,176,25-06-2018,3,0,6,0,1,1,1,28.495000,32.165650,48.3333,14.041257,1782,3420,5202
176,177,26-06-2018,3,0,6,0,2,1,1,27.880000,31.881450,51.3333,6.333731,1920,3385,5305
177,178,27-06-2018,3,0,6,0,3,1,2,27.982500,31.850200,65.8333,7.208396,854,3854,4708
178,179,28-06-2018,3,0,6,0,4,1,1,30.510847,34.627900,63.4167,9.666961,732,3916,4648
179,180,29-06-2018,3,0,6,0,5,1,1,29.861653,32.734400,49.7917,17.542007,848,4377,5225
180,181,30-06-2018,3,0,6,0,6,0,1,28.563347,31.850400,43.4167,12.415904,1027,4488,5515
181,182,01-07-2018,3,0,7,0,0,0,1,29.622500,32.608100,39.6250,6.874736,1246,4116,5362
182,183,02-07-2018,3,0,7,0,1,1,1,30.271653,33.365400,44.4583,7.709154,2204,2915,5119
183,184,03-07-2018,3,0,7,0,2,1,2,29.383347,33.428750,68.2500,15.333486,2282,2367,4649
184,185,04-07-2018,3,0,7,1,3,0,2,29.793347,33.270850,63.7917,5.459106,3065,2978,6043
185,186,05-07-2018,3,0,7,0,4,1,1,30.613347,34.816900,59.0417,8.459286,1031,3634,4665
186,187,06-07-2018,3,0,7,0,5,1,1,29.520000,34.281650,74.3333,10.042161,784,3845,4629
187,188,07-07-2018,3,0,7,0,6,0,1,30.750000,34.343550,65.1250,10.666400,754,3838,4592
188,189,08-07-2018,3,0,7,0,0,0,2,29.075847,33.524150,75.7917,15.083643,692,3348,4040
189,190,09-07-2018,3,0,7,0,1,1,1,30.066653,33.207900,60.9167,11.250104,1988,3348,5336
190,191,10-07-2018,3,0,7,0,2,1,1,30.647500,34.501250,57.8333,12.292557,1743,3138,4881
191,192,11-07-2018,3,0,7,0,3,1,1,31.262500,36.490200,63.5833,18.916579,723,3363,4086
192,193,12-07-2018,3,0,7,0,4,1,1,32.560847,36.963750,55.9167,13.417018,662,3596,4258
193,194,13-07-2018,3,0,7,0,5,1,1,30.613347,34.470200,63.1667,9.790911,748,3594,4342
194,195,14-07-2018,3,0,7,0,6,0,1,27.914153,31.755200,47.6250,16.124689,888,4196,5084
195,196,15-07-2018,3,0,7,0,0,0,1,27.196653,31.218550,59.1250,12.249811,1318,4220,5538
196,197,16-07-2018,3,0,7,0,1,1,1,28.153347,31.913150,58.5000,13.958914,2418,3505,5923
197,198,17-07-2018,3,0,7,0,2,1,1,29.485847,33.491650,60.4167,16.417211,2006,3296,5302
198,199,18-07-2018,3,0,7,0,3,1,1,30.613347,35.196250,65.1250,14.458868,841,3617,4458
199,200,19-07-2018,3,0,7,0,4,1,1,31.843347,37.373950,65.0417,8.750200,752,3789,4541
200,201,20-07-2018,3,0,7,0,5,1,1,31.501653,37.342500,70.7083,7.625739,644,3688,4332
201,202,21-07-2018,3,0,7,0,6,0,2,33.415000,41.318550,69.1250,14.875407,632,3152,3784
202,203,22-07-2018,3,0,7,0,0,0,1,34.781653,42.044800,58.0417,8.917700,562,2825,3387
203,204,23-07-2018,3,0,7,0,1,1,1,34.815847,40.214350,50.0000,8.791807,987,2298,3285
204,205,24-07-2018,3,0,7,0,2,1,1,34.030000,39.741450,55.0833,11.334457,1050,2556,3606
205,206,25-07-2018,3,0,7,0,3,1,1,30.476653,36.047900,75.7083,6.084156,568,3272,3840
206,207,26-07-2018,3,0,7,0,4,1,1,31.638347,34.848950,54.0833,13.417286,750,3840,4590
207,208,27-07-2018,3,0,7,0,5,1,1,31.775000,34.533350,40.2917,12.292021,755,3901,4656
208,209,28-07-2018,3,0,7,0,6,0,1,31.945847,36.995000,58.3333,11.958093,606,3784,4390
209,210,29-07-2018,3,0,7,0,0,0,1,34.371653,39.298350,54.2500,11.667246,670,3176,3846
210,211,30-07-2018,3,0,7,0,1,1,1,32.970847,36.426850,46.5833,11.291979,1559,2916,4475
211,212,31-07-2018,3,0,7,0,2,1,1,33.039153,36.489800,48.0833,11.042471,1524,2778,4302
212,213,01-08-2018,3,0,8,0,3,1,1,31.638347,35.164600,55.0833,10.500039,729,3537,4266
213,214,02-08-2018,3,0,8,0,4,1,1,32.116653,35.353550,49.1250,13.791950,801,4044,4845
214,215,03-08-2018,3,0,8,0,5,1,2,29.998347,33.996850,65.7500,9.084061,467,3107,3574
215,216,04-08-2018,3,0,8,0,6,0,2,29.110000,33.239400,75.7500,13.209050,799,3777,4576
216,217,05-08-2018,3,0,8,0,0,0,1,29.144153,32.828350,63.0833,12.374632,1023,3843,4866
217,218,06-08-2018,3,0,8,0,1,1,2,29.383347,33.807700,75.5000,15.292750,1521,2773,4294
218,219,07-08-2018,3,0,8,0,2,1,1,30.442500,35.764600,75.2917,13.499629,1298,2487,3785
219,220,08-08-2018,3,0,8,0,3,1,1,31.365000,35.164150,59.2083,12.875725,846,3480,4326
220,221,09-08-2018,3,0,8,0,4,1,1,31.775000,36.206050,57.0417,10.125107,907,3695,4602
221,222,10-08-2018,3,0,8,0,5,1,1,31.433347,34.249150,42.4167,13.417286,884,3896,4780
222,223,11-08-2018,3,0,8,0,6,0,1,29.417500,32.576050,42.3750,11.041332,812,3980,4792
223,224,12-08-2018,3,0,8,0,0,0,1,29.041653,32.702100,41.5000,8.416607,1051,3854,4905
224,225,13-08-2018,3,0,8,0,1,1,2,28.119153,32.292900,72.9583,14.167418,1504,2646,4150
225,226,14-08-2018,3,0,8,0,2,1,2,27.743347,31.219400,81.7500,14.916411,1338,2482,3820
226,227,15-08-2018,3,0,8,0,3,1,1,27.299153,30.808350,71.2083,13.999918,775,3563,4338
227,228,16-08-2018,3,0,8,0,4,1,1,28.734153,32.291850,57.8333,15.834043,721,4004,4725
228,229,17-08-2018,3,0,8,0,5,1,1,29.656653,33.333550,57.5417,9.625689,668,4026,4694
229,230,18-08-2018,3,0,8,0,6,0,1,29.178347,33.112900,65.4583,15.624936,639,3166,3805
230,231,19-08-2018,3,0,8,0,0,0,2,28.085000,31.661050,72.2917,9.333636,797,3356,4153
231,232,20-08-2018,3,0,8,0,1,1,1,28.597500,32.449800,67.4167,6.999289,1914,3277,5191
232,233,21-08-2018,3,0,8,0,2,1,1,29.144153,33.776250,77.0000,16.666518,1249,2624,3873
233,234,22-08-2018,3,0,8,0,3,1,1,28.358347,31.912700,47.0000,18.542250,833,3925,4758
234,235,23-08-2018,3,0,8,0,4,1,1,26.274153,30.303350,45.5417,9.833121,1281,4614,5895
235,236,24-08-2018,3,0,8,0,5,1,1,27.606653,31.534600,60.5000,16.958236,949,4181,5130
236,237,25-08-2018,3,0,8,0,6,0,2,28.050847,32.292700,77.1667,14.125811,435,3107,3542
237,238,26-08-2018,3,0,8,0,0,0,1,28.700000,32.986650,76.1250,5.625488,768,3893,4661

In [79]:
#df.head(n) ----> head function is to see top n rows of the data
df.head(5)

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,01-01-2018,1,0,1,0,1,1,2,14.110847,18.18125,80.5833,10.749882,331,654,985
1,2,02-01-2018,1,0,1,0,2,1,2,14.902598,17.68695,69.6087,16.652113,131,670,801
2,3,03-01-2018,1,0,1,0,3,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349
3,4,04-01-2018,1,0,1,0,4,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562
4,5,05-01-2018,1,0,1,0,5,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600

In [71]:
df.tail(4)

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
726,727,28-12-2019,1,1,12,0,6,0,2,10.386653,12.75230,59.0000,10.416557,644,2451,3095
727,728,29-12-2019,1,1,12,0,0,0,2,10.386653,12.12000,75.2917,8.333661,159,1182,1341
728,729,30-12-2019,1,1,12,0,1,1,1,10.489153,11.58500,48.3333,23.500518,364,1432,1796
729,730,31-12-2019,1,1,12,0,2,1,2,8.849153,11.17435,57.7500,10.374682,439,2290,2729

In [6]:
df

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,01-01-2018,1,0,1,0,1,1,2,14.110847,18.18125,80.5833,10.749882,331,654,985
1,2,02-01-2018,1,0,1,0,2,1,2,14.902598,17.68695,69.6087,16.652113,131,670,801
2,3,03-01-2018,1,0,1,0,3,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349
3,4,04-01-2018,1,0,1,0,4,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562
4,5,05-01-2018,1,0,1,0,5,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725,726,27-12-2019,1,1,12,0,5,1,2,10.420847,11.33210,65.2917,23.458911,247,1867,2114
726,727,28-12-2019,1,1,12,0,6,0,2,10.386653,12.75230,59.0000,10.416557,644,2451,3095
727,728,29-12-2019,1,1,12,0,0,0,2,10.386653,12.12000,75.2917,8.333661,159,1182,1341
728,729,30-12-2019,1,1,12,0,1,1,1,10.489153,11.58500,48.3333,23.500518,364,1432,1796
729,730,31-12-2019,1,1,12,0,2,1,2,8.849153,11.17435,57.7500,10.374682,439,2290,2729

In [7]:
##check intire dataframe
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
df

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,01-01-2018,1,0,1,0,1,1,2,14.110847,18.181250,80.5833,10.749882,331,654,985
1,2,02-01-2018,1,0,1,0,2,1,2,14.902598,17.686950,69.6087,16.652113,131,670,801
2,3,03-01-2018,1,0,1,0,3,1,1,8.050924,9.470250,43.7273,16.636703,120,1229,1349
3,4,04-01-2018,1,0,1,0,4,1,1,8.200000,10.606100,59.0435,10.739832,108,1454,1562
4,5,05-01-2018,1,0,1,0,5,1,1,9.305237,11.463500,43.6957,12.522300,82,1518,1600
5,6,06-01-2018,1,0,1,0,6,0,1,8.378268,11.660450,51.8261,6.000868,88,1518,1606
6,7,07-01-2018,1,0,1,0,0,0,2,8.057402,10.441950,49.8696,11.304642,148,1362,1510
7,8,08-01-2018,1,0,1,0,1,1,2,6.765000,8.112700,53.5833,17.875868,68,891,959
8,9,09-01-2018,1,0,1,0,2,1,1,5.671653,5.808750,43.4167,24.250650,54,768,822
9,10,10-01-2018,1,0,1,0,3,1,1,6.184153,7.544400,48.2917,14.958889,41,1280,1321
10,11,11-01-2018,1,0,1,0,4,1,2,6.932731,9.573200,68.6364,8.182844,43,1220,1263
11,12,12-01-2018,1,0,1,0,5,1,1,7.081807,8.023650,59.9545,20.410009,25,1137,1162
12,13,13-01-2018,1,0,1,0,6,0,1,6.765000,7.544150,47.0417,20.167000,38,1368,1406
13,14,14-01-2018,1,0,1,0,0,0,1,6.595670,9.420650,53.7826,8.478716,54,1367,1421
14,15,15-01-2018,1,0,1,0,1,1,2,9.566653,12.405600,49.8750,10.583521,222,1026,1248
15,16,16-01-2018,1,0,1,0,2,1,1,9.498347,11.710850,48.3750,12.625011,251,953,1204
16,17,17-01-2018,1,0,1,1,3,0,2,7.209153,8.838550,53.7500,12.999139,117,883,1000
17,18,18-01-2018,1,0,1,0,4,1,2,8.883347,11.616650,86.1667,9.833925,9,674,683
18,19,19-01-2018,1,0,1,0,5,1,2,11.979134,14.921100,74.1739,13.957239,78,1572,1650
19,20,20-01-2018,1,0,1,0,6,0,2,10.728347,12.752500,53.8333,13.125568,83,1844,1927
20,21,21-01-2018,1,0,1,0,0,0,1,7.277500,7.891650,45.7083,23.667214,75,1468,1543
21,22,22-01-2018,1,0,1,0,1,1,1,2.424346,3.953480,40.0000,11.521990,93,888,981
22,23,23-01-2018,1,0,1,0,2,1,1,3.957390,4.941955,43.6522,16.522200,150,836,986
23,24,24-01-2018,1,0,1,0,3,1,1,3.993043,5.896500,49.1739,10.608110,86,1330,1416
24,25,25-01-2018,1,0,1,0,4,1,2,9.162598,11.726300,61.6957,8.696332,186,1799,1985
25,26,26-01-2018,1,0,1,0,5,1,3,8.917500,10.180000,86.2500,19.687950,34,472,506
26,27,27-01-2018,1,0,1,0,6,0,1,7.995000,10.985000,68.7500,7.627079,15,416,431
27,28,28-01-2018,1,0,1,0,0,0,2,8.342598,11.165850,79.3043,8.261100,38,1129,1167
28,29,29-01-2018,1,0,1,0,1,1,1,8.057402,10.606300,65.1739,9.739455,123,975,1098
29,30,30-01-2018,1,0,1,0,2,1,1,8.877402,12.516100,72.2174,4.956834,140,956,1096
30,31,31-01-2018,1,0,1,0,3,1,2,7.414153,9.312500,60.3750,12.541864,42,1459,1501
31,32,01-02-2018,1,0,2,0,4,1,2,7.879134,11.726500,82.9565,3.565271,47,1313,1360
32,33,02-02-2018,1,0,2,0,5,1,2,10.660000,12.720850,77.5417,17.708636,72,1454,1526
33,34,03-02-2018,1,0,2,0,6,0,1,7.665237,8.893900,43.7826,18.609384,61,1489,1550
34,35,04-02-2018,1,0,2,0,0,0,2,8.663464,11.429350,58.5217,8.565213,88,1620,1708
35,36,05-02-2018,1,0,2,0,1,1,2,9.566653,12.152900,92.9167,10.792293,100,905,1005
36,37,06-02-2018,1,0,2,0,2,1,1,11.719153,14.583550,56.8333,9.500600,354,1269,1623
37,38,07-02-2018,1,0,2,0,3,1,1,11.138347,15.182900,73.8333,3.042356,120,1592,1712
38,39,08-02-2018,1,0,2,0,4,1,1,9.054153,9.912300,53.7917,24.250650,64,1466,1530
39,40,09-02-2018,1,0,2,0,5,1,2,5.526103,7.214150,49.4783,12.652213,53,1552,1605
40,41,10-02-2018,1,0,2,0,6,0,1,5.918268,7.477400,43.7391,14.869645,47,1491,1538
41,42,11-02-2018,1,0,2,0,0,0,1,7.752731,10.675450,50.6364,7.272850,149,1597,1746
42,43,12-02-2018,1,0,2,0,1,1,1,9.122500,11.647700,54.4167,13.625589,288,1184,1472
43,44,13-02-2018,1,0,2,0,2,1,1,12.977402,16.205650,45.7391,17.479161,397,1192,1589
44,45,14-02-2018,1,0,2,0,3,1,1,17.015000,19.917500,37.5833,27.999836,208,1705,1913
45,46,15-02-2018,1,0,2,0,4,1,1,10.909567,12.713700,31.4348,19.522058,140,1675,1815
46,47,16-02-2018,1,0,2,0,5,1,1,13.048701,15.810000,42.3478,16.869997,218,1897,2115
47,48,17-02-2018,1,0,2,0,6,0,1,17.869153,21.432900,50.5000,15.416968,259,2216,2475
48,49,18-02-2018,1,0,2,0,0,0,1,21.388347,25.599150,51.6667,17.749975,579,2348,2927
49,50,19-02-2018,1,0,2,0,1,1,1,16.365847,19.570200,18.7917,34.000021,532,1103,1635
50,51,20-02-2018,1,0,2,0,2,1,1,11.693897,13.866500,40.7826,14.956745,639,1173,1812
51,52,21-02-2018,1,0,2,1,3,0,2,12.436653,14.203750,60.5000,20.625682,195,912,1107
52,53,22-02-2018,1,0,2,0,4,1,1,7.471102,9.301650,57.7778,13.110761,74,1376,1450
53,54,23-02-2018,1,0,2,0,5,1,1,9.091299,12.285850,42.3043,6.305571,139,1778,1917
54,55,24-02-2018,1,0,2,0,6,0,2,12.121732,14.459550,69.7391,16.783232,100,1707,1807
55,56,25-02-2018,1,0,2,0,0,0,2,14.938268,17.523050,71.2174,23.218113,120,1341,1461
56,57,26-02-2018,1,0,2,0,1,1,1,11.582500,14.109600,53.7917,12.500257,424,1545,1969
57,58,27-02-2018,1,0,2,0,2,1,1,14.082598,17.555450,68.0000,8.391616,694,1708,2402
58,59,28-02-2018,1,0,2,0,3,1,2,16.698193,20.005900,87.6364,19.408962,81,1365,1446
59,60,01-03-2018,1,0,3,0,4,1,1,10.933347,13.193950,53.5000,14.500475,137,1714,1851
60,61,02-03-2018,1,0,3,0,5,1,1,13.735000,16.003550,44.9583,20.624811,231,1903,2134
61,62,03-03-2018,1,0,3,0,6,0,1,8.131653,10.006650,31.8333,15.125518,123,1562,1685
62,63,04-03-2018,1,0,3,0,0,0,2,10.728347,12.783950,61.0417,13.624182,214,1730,1944
63,64,05-03-2018,1,0,3,0,1,1,2,15.750847,18.938950,78.9167,16.875357,640,1437,2077
64,65,06-03-2018,1,0,3,0,2,1,2,15.437402,18.312600,94.8261,23.000229,114,491,605
65,66,07-03-2018,1,0,3,0,3,1,1,10.731299,11.923050,55.1304,22.870584,244,1628,1872
66,67,08-03-2018,1,0,3,0,4,1,1,11.992500,15.120000,42.0833,8.083550,316,1817,2133
67,68,09-03-2018,1,0,3,0,5,1,2,12.129153,14.330400,77.5417,14.750050,191,1700,1891
68,69,10-03-2018,1,0,3,0,6,0,3,15.952731,19.283400,0.0000,17.545759,46,577,623
69,70,11-03-2018,1,0,3,0,0,0,2,12.977402,15.250000,64.9565,15.608990,247,1730,1977
70,71,12-03-2018,1,0,3,0,1,1,1,13.495847,16.287500,59.4583,14.791925,724,1408,2132
71,72,13-03-2018,1,0,3,0,2,1,1,15.758268,19.004550,52.7391,18.130468,982,1435,2417
72,73,14-03-2018,1,0,3,0,3,1,1,13.333897,16.600000,49.6957,9.174042,359,1687,2046
73,74,15-03-2018,1,0,3,0,4,1,2,13.013031,15.908900,65.5652,12.348703,289,1767,2056
74,75,16-03-2018,1,0,3,0,5,1,2,14.973897,18.346500,77.6522,13.608839,321,1871,2192
75,76,17-03-2018,1,0,3,0,6,0,1,17.015000,20.516650,60.2917,14.041793,424,2320,2744
76,77,18-03-2018,1,0,3,0,0,0,1,22.140000,26.350450,52.5217,15.478139,884,2355,3239
77,78,19-03-2018,1,0,3,0,1,1,1,19.372500,23.326250,37.9167,24.667189,1424,1693,3117
78,79,20-03-2018,1,0,3,0,2,1,1,13.632500,16.287500,47.3750,13.917307,1047,1424,2471
79,80,21-03-2018,2,0,3,0,3,1,2,17.647835,20.486750,73.7391,19.348461,401,1676,2077
80,81,22-03-2018,2,0,3,0,4,1,1,18.108347,22.032100,62.4583,15.125250,460,2243,2703
81,82,23-03-2018,2,0,3,0,5,1,2,14.225237,16.896950,83.9565,15.695487,203,1918,2121
82,83,24-03-2018,2,0,3,0,6,0,2,11.685000,13.541650,80.5833,16.333729,166,1699,1865
83,84,25-03-2018,2,0,3,0,0,0,1,10.830847,12.815600,49.5000,15.458575,300,1910,2210
84,85,26-03-2018,2,0,3,0,1,1,1,10.899153,12.878550,39.4167,14.041257,981,1515,2496
85,86,27-03-2018,2,0,3,0,2,1,2,10.374763,12.516950,49.3913,12.348100,472,1221,1693
86,87,28-03-2018,2,0,3,0,3,1,1,10.838268,12.878700,30.2174,14.217668,222,1806,2028
87,88,29-03-2018,2,0,3,0,4,1,1,12.402500,14.645400,31.4167,15.208732,317,2108,2425
88,89,30-03-2018,2,0,3,0,5,1,2,12.300000,14.867500,64.6667,11.583496,168,1368,1536
89,90,31-03-2018,2,0,3,0,6,0,3,11.001653,12.878750,91.8333,14.582282,179,1506,1685
90,91,01-04-2018,2,0,4,0,0,0,2,12.300000,14.172700,68.6250,17.333436,307,1920,2227
91,92,02-04-2018,2,0,4,0,1,1,2,12.915000,15.781850,65.3750,13.208782,898,1354,2252
92,93,03-04-2018,2,0,4,0,2,1,1,15.511653,18.938350,48.0000,12.208271,1651,1598,3249
93,94,04-04-2018,2,0,4,0,3,1,1,23.506653,27.146450,42.6250,25.833257,734,2381,3115
94,95,05-04-2018,2,0,4,0,4,1,2,16.980847,19.917500,64.2083,26.000489,167,1628,1795
95,96,06-04-2018,2,0,4,0,5,1,1,16.024153,19.380400,47.0833,17.625221,413,2395,2808
96,97,07-04-2018,2,0,4,0,6,0,1,17.937500,21.684800,60.2917,10.874904,571,2570,3141
97,98,08-04-2018,2,0,4,0,0,0,2,13.769153,16.223950,83.6250,15.208464,172,1299,1471
98,99,09-04-2018,2,0,4,0,1,1,2,14.042500,17.076450,87.7500,8.916561,879,1576,2455
99,100,10-04-2018,2,0,4,0,2,1,2,17.493347,21.336850,85.7500,9.833389,1188,1707,2895
100,101,11-04-2018,2,0,4,0,3,1,2,24.421732,28.260850,71.6956,21.739758,855,2493,3348
101,102,12-04-2018,2,0,4,0,4,1,2,20.602500,24.652700,73.9167,18.416893,257,1777,2034
102,103,13-04-2018,2,0,4,0,5,1,2,16.912500,20.864150,81.9167,16.791339,209,1953,2162
103,104,14-04-2018,2,0,4,0,6,0,1,19.167500,23.137100,54.0417,7.416900,529,2738,3267
104,105,15-04-2018,2,0,4,1,0,0,1,18.313347,22.095650,67.1250,15.167125,642,2484,3126
105,106,16-04-2018,2,0,4,0,1,1,3,17.664153,21.274600,88.8333,22.834136,121,674,795
106,107,17-04-2018,2,0,4,0,2,1,1,18.723347,22.284800,47.9583,20.334232,1558,2186,3744
107,108,18-04-2018,2,0,4,0,3,1,1,21.012500,25.157300,54.2500,10.958989,669,2760,3429
108,109,19-04-2018,2,0,4,0,4,1,2,20.739153,24.462900,66.5833,10.584057,409,2795,3204
109,110,20-04-2018,2,0,4,0,5,1,1,24.395000,28.219600,61.4167,16.208975,613,3331,3944
110,111,21-04-2018,2,0,4,0,6,0,1,18.825847,22.694600,40.7083,21.792286,745,3444,4189
111,112,22-04-2018,2,0,4,0,0,0,2,13.803347,16.097700,72.9583,14.707907,177,1506,1683
112,113,23-04-2018,2,0,4,0,1,1,2,18.860000,22.506050,88.7917,15.458575,1462,2574,4036
113,114,24-04-2018,2,0,4,0,2,1,2,23.848347,27.588150,81.0833,12.875725,1710,2481,4191
114,115,25-04-2018,2,0,4,0,3,1,1,24.873347,28.725000,77.6667,12.417311,773,3300,4073
115,116,26-04-2018,2,0,4,0,4,1,1,25.898347,29.704150,72.9167,21.875500,678,3722,4400
116,117,27-04-2018,2,0,4,0,5,1,2,25.420000,28.757100,83.5417,20.917400,547,3325,3872
117,118,28-04-2018,2,0,4,0,6,0,2,25.317500,28.946450,70.0833,21.500836,569,3489,4058
118,119,29-04-2018,2,0,4,0,0,0,1,20.910000,24.873150,45.7083,16.084221,878,3717,4595
119,120,30-04-2018,2,0,4,0,1,1,1,19.372500,23.201050,50.3333,15.750025,1965,3347,5312
120,121,01-05-2018,2,0,5,0,2,1,2,18.518347,22.410200,76.2083,7.125718,1138,2213,3351
121,122,02-05-2018,2,0,5,0,3,1,2,22.515847,26.641650,73.0000,12.291418,847,3554,4401
122,123,03-05-2018,2,0,5,0,4,1,2,25.283347,29.103950,69.7083,22.958689,603,3848,4451
123,124,04-05-2018,2,0,5,0,5,1,2,16.980847,20.232500,73.7083,22.042732,255,2378,2633
124,125,05-05-2018,2,0,5,0,6,0,1,18.825847,22.095850,44.4167,19.791264,614,3819,4433
125,126,06-05-2018,2,0,5,0,0,0,1,19.645847,23.705850,59.0000,15.292482,894,3714,4608
126,127,07-05-2018,2,0,5,0,1,1,1,21.320000,25.631050,54.1250,10.750150,1612,3102,4714
127,128,08-05-2018,2,0,5,0,2,1,1,21.661653,25.946650,63.1667,5.000712,1401,2932,4333
128,129,09-05-2018,2,0,5,0,3,1,1,21.832500,26.262300,58.8750,11.792000,664,3698,4362
129,130,10-05-2018,2,0,5,0,4,1,1,21.832500,26.136050,48.9167,7.749957,694,4109,4803
130,131,11-05-2018,2,0,5,0,5,1,1,22.242500,26.420000,63.2917,8.083014,550,3632,4182
131,132,12-05-2018,2,0,5,0,6,0,1,21.935000,26.168150,74.7500,12.707689,695,4169,4864
132,133,13-05-2018,2,0,5,0,0,0,2,21.012500,24.715000,86.3333,12.041575,692,3413,4105
133,134,14-05-2018,2,0,5,0,1,1,2,21.354153,25.031450,92.2500,9.041650,902,2507,3409
134,135,15-05-2018,2,0,5,0,2,1,2,23.062500,26.800000,86.7083,10.249593,1582,2971,4553
135,136,16-05-2018,2,0,5,0,3,1,1,23.677500,27.525600,78.7917,8.500357,773,3185,3958
136,137,17-05-2018,2,0,5,0,4,1,2,23.028347,26.926450,83.7917,18.582718,678,3445,4123
137,138,18-05-2018,2,0,5,0,5,1,2,22.550000,26.357900,87.0000,13.499964,536,3319,3855
138,139,19-05-2018,2,0,5,0,6,0,2,21.764153,25.537100,82.9583,7.250271,735,3840,4575
139,140,20-05-2018,2,0,5,0,0,0,1,22.003347,26.452100,71.9583,8.375871,909,4008,4917
140,141,21-05-2018,2,0,5,0,1,1,1,24.702500,28.598750,62.6667,8.083550,2258,3547,5805
141,142,22-05-2018,2,0,5,0,2,1,1,24.770847,28.725000,74.9583,9.916536,1576,3084,4660
142,143,23-05-2018,2,0,5,0,3,1,2,25.898347,29.514800,81.0000,15.667414,836,3438,4274
143,144,24-05-2018,2,0,5,0,4,1,2,27.060000,30.240650,74.0833,13.875164,659,3833,4492
144,145,25-05-2018,2,0,5,0,5,1,1,27.094153,30.777100,69.6250,10.333611,740,4238,4978
145,146,26-05-2018,2,0,5,0,6,0,1,29.041653,32.734400,67.7500,13.376014,758,3919,4677
146,147,27-05-2018,2,0,5,0,0,0,1,27.948347,31.850400,65.3750,16.125493,871,3808,4679
147,148,28-05-2018,2,0,5,0,1,1,1,26.889153,30.618950,72.9583,15.416164,2001,2757,4758
148,149,29-05-2018,2,0,5,0,2,1,1,27.367500,30.777500,81.8750,14.333846,2355,2433,4788
149,150,30-05-2018,2,0,5,1,3,0,1,30.066653,33.554600,68.5000,8.792075,1549,2549,4098
150,151,31-05-2018,2,0,5,0,4,1,1,31.775000,36.269150,63.6667,7.459043,673,3309,3982
151,152,01-06-2018,2,0,6,0,5,1,2,31.330847,36.048350,67.7083,13.875164,513,3461,3974
152,153,02-06-2018,2,0,6,0,6,0,1,29.315000,32.197100,30.5000,19.583229,736,4232,4968
153,154,03-06-2018,2,0,6,0,0,0,1,25.420000,29.356650,35.4167,16.959107,898,4414,5312
154,155,04-06-2018,2,0,6,0,1,1,1,26.035000,29.734800,45.6250,8.250514,1869,3473,5342
155,156,05-06-2018,2,0,6,0,2,1,2,26.581653,30.840200,65.2500,9.292364,1685,3221,4906
156,157,06-06-2018,2,0,6,0,3,1,1,27.811653,31.092900,60.0000,8.167032,673,3875,4548
157,158,07-06-2018,2,0,6,0,4,1,1,29.007500,32.797500,59.7917,12.583136,763,4070,4833
158,159,08-06-2018,2,0,6,0,5,1,1,31.809153,36.363950,62.2083,9.166739,676,3725,4401
159,160,09-06-2018,2,0,6,0,6,0,2,33.141653,37.878950,56.8333,10.042161,563,3352,3915
160,161,10-06-2018,2,0,6,0,0,0,1,30.955000,35.164600,60.5000,9.417118,815,3771,4586
161,162,11-06-2018,2,0,6,0,1,1,1,29.725000,33.901900,65.4583,10.374950,1729,3237,4966
162,163,12-06-2018,2,0,6,0,2,1,1,28.392500,32.166250,74.7917,10.958989,1467,2993,4460
163,164,13-06-2018,2,0,6,0,3,1,1,26.035000,30.082700,49.4583,20.458450,863,4157,5020
164,165,14-06-2018,2,0,6,0,4,1,1,24.770847,29.577300,50.7083,18.041961,727,4164,4891
165,166,15-06-2018,2,0,6,0,5,1,1,25.693347,29.387700,47.1667,11.250104,769,4411,5180
166,167,16-06-2018,2,0,6,0,6,0,2,25.761653,29.767300,68.8333,13.833557,545,3222,3767
167,168,17-06-2018,2,0,6,0,0,0,1,26.615847,30.019150,73.5833,9.582943,863,3981,4844
168,169,18-06-2018,2,0,6,0,1,1,1,28.563347,32.197700,67.0417,8.000336,1807,3312,5119
169,170,19-06-2018,2,0,6,0,2,1,2,28.665847,32.292300,66.6667,6.834000,1639,3105,4744
170,171,20-06-2018,2,0,6,0,3,1,2,26.035000,29.767300,74.6250,10.416825,699,3311,4010
171,172,21-06-2018,3,0,6,0,4,1,2,27.914153,31.882300,77.0417,11.458675,774,4061,4835
172,173,22-06-2018,3,0,6,0,5,1,1,30.066653,34.691450,70.7500,11.541554,661,3846,4507
173,174,23-06-2018,3,0,6,0,6,0,2,29.861653,34.691650,70.3333,15.999868,746,4044,4790
174,175,24-06-2018,3,0,6,0,0,0,1,29.690847,32.829150,57.3333,14.875675,969,4022,4991
175,176,25-06-2018,3,0,6,0,1,1,1,28.495000,32.165650,48.3333,14.041257,1782,3420,5202
176,177,26-06-2018,3,0,6,0,2,1,1,27.880000,31.881450,51.3333,6.333731,1920,3385,5305
177,178,27-06-2018,3,0,6,0,3,1,2,27.982500,31.850200,65.8333,7.208396,854,3854,4708
178,179,28-06-2018,3,0,6,0,4,1,1,30.510847,34.627900,63.4167,9.666961,732,3916,4648
179,180,29-06-2018,3,0,6,0,5,1,1,29.861653,32.734400,49.7917,17.542007,848,4377,5225
180,181,30-06-2018,3,0,6,0,6,0,1,28.563347,31.850400,43.4167,12.415904,1027,4488,5515
181,182,01-07-2018,3,0,7,0,0,0,1,29.622500,32.608100,39.6250,6.874736,1246,4116,5362
182,183,02-07-2018,3,0,7,0,1,1,1,30.271653,33.365400,44.4583,7.709154,2204,2915,5119
183,184,03-07-2018,3,0,7,0,2,1,2,29.383347,33.428750,68.2500,15.333486,2282,2367,4649
184,185,04-07-2018,3,0,7,1,3,0,2,29.793347,33.270850,63.7917,5.459106,3065,2978,6043
185,186,05-07-2018,3,0,7,0,4,1,1,30.613347,34.816900,59.0417,8.459286,1031,3634,4665
186,187,06-07-2018,3,0,7,0,5,1,1,29.520000,34.281650,74.3333,10.042161,784,3845,4629
187,188,07-07-2018,3,0,7,0,6,0,1,30.750000,34.343550,65.1250,10.666400,754,3838,4592
188,189,08-07-2018,3,0,7,0,0,0,2,29.075847,33.524150,75.7917,15.083643,692,3348,4040
189,190,09-07-2018,3,0,7,0,1,1,1,30.066653,33.207900,60.9167,11.250104,1988,3348,5336
190,191,10-07-2018,3,0,7,0,2,1,1,30.647500,34.501250,57.8333,12.292557,1743,3138,4881
191,192,11-07-2018,3,0,7,0,3,1,1,31.262500,36.490200,63.5833,18.916579,723,3363,4086
192,193,12-07-2018,3,0,7,0,4,1,1,32.560847,36.963750,55.9167,13.417018,662,3596,4258
193,194,13-07-2018,3,0,7,0,5,1,1,30.613347,34.470200,63.1667,9.790911,748,3594,4342
194,195,14-07-2018,3,0,7,0,6,0,1,27.914153,31.755200,47.6250,16.124689,888,4196,5084
195,196,15-07-2018,3,0,7,0,0,0,1,27.196653,31.218550,59.1250,12.249811,1318,4220,5538
196,197,16-07-2018,3,0,7,0,1,1,1,28.153347,31.913150,58.5000,13.958914,2418,3505,5923
197,198,17-07-2018,3,0,7,0,2,1,1,29.485847,33.491650,60.4167,16.417211,2006,3296,5302
198,199,18-07-2018,3,0,7,0,3,1,1,30.613347,35.196250,65.1250,14.458868,841,3617,4458
199,200,19-07-2018,3,0,7,0,4,1,1,31.843347,37.373950,65.0417,8.750200,752,3789,4541
200,201,20-07-2018,3,0,7,0,5,1,1,31.501653,37.342500,70.7083,7.625739,644,3688,4332
201,202,21-07-2018,3,0,7,0,6,0,2,33.415000,41.318550,69.1250,14.875407,632,3152,3784
202,203,22-07-2018,3,0,7,0,0,0,1,34.781653,42.044800,58.0417,8.917700,562,2825,3387
203,204,23-07-2018,3,0,7,0,1,1,1,34.815847,40.214350,50.0000,8.791807,987,2298,3285
204,205,24-07-2018,3,0,7,0,2,1,1,34.030000,39.741450,55.0833,11.334457,1050,2556,3606
205,206,25-07-2018,3,0,7,0,3,1,1,30.476653,36.047900,75.7083,6.084156,568,3272,3840
206,207,26-07-2018,3,0,7,0,4,1,1,31.638347,34.848950,54.0833,13.417286,750,3840,4590
207,208,27-07-2018,3,0,7,0,5,1,1,31.775000,34.533350,40.2917,12.292021,755,3901,4656
208,209,28-07-2018,3,0,7,0,6,0,1,31.945847,36.995000,58.3333,11.958093,606,3784,4390
209,210,29-07-2018,3,0,7,0,0,0,1,34.371653,39.298350,54.2500,11.667246,670,3176,3846
210,211,30-07-2018,3,0,7,0,1,1,1,32.970847,36.426850,46.5833,11.291979,1559,2916,4475
211,212,31-07-2018,3,0,7,0,2,1,1,33.039153,36.489800,48.0833,11.042471,1524,2778,4302
212,213,01-08-2018,3,0,8,0,3,1,1,31.638347,35.164600,55.0833,10.500039,729,3537,4266
213,214,02-08-2018,3,0,8,0,4,1,1,32.116653,35.353550,49.1250,13.791950,801,4044,4845
214,215,03-08-2018,3,0,8,0,5,1,2,29.998347,33.996850,65.7500,9.084061,467,3107,3574
215,216,04-08-2018,3,0,8,0,6,0,2,29.110000,33.239400,75.7500,13.209050,799,3777,4576
216,217,05-08-2018,3,0,8,0,0,0,1,29.144153,32.828350,63.0833,12.374632,1023,3843,4866
217,218,06-08-2018,3,0,8,0,1,1,2,29.383347,33.807700,75.5000,15.292750,1521,2773,4294
218,219,07-08-2018,3,0,8,0,2,1,1,30.442500,35.764600,75.2917,13.499629,1298,2487,3785
219,220,08-08-2018,3,0,8,0,3,1,1,31.365000,35.164150,59.2083,12.875725,846,3480,4326
220,221,09-08-2018,3,0,8,0,4,1,1,31.775000,36.206050,57.0417,10.125107,907,3695,4602
221,222,10-08-2018,3,0,8,0,5,1,1,31.433347,34.249150,42.4167,13.417286,884,3896,4780
222,223,11-08-2018,3,0,8,0,6,0,1,29.417500,32.576050,42.3750,11.041332,812,3980,4792
223,224,12-08-2018,3,0,8,0,0,0,1,29.041653,32.702100,41.5000,8.416607,1051,3854,4905
224,225,13-08-2018,3,0,8,0,1,1,2,28.119153,32.292900,72.9583,14.167418,1504,2646,4150
225,226,14-08-2018,3,0,8,0,2,1,2,27.743347,31.219400,81.7500,14.916411,1338,2482,3820
226,227,15-08-2018,3,0,8,0,3,1,1,27.299153,30.808350,71.2083,13.999918,775,3563,4338
227,228,16-08-2018,3,0,8,0,4,1,1,28.734153,32.291850,57.8333,15.834043,721,4004,4725
228,229,17-08-2018,3,0,8,0,5,1,1,29.656653,33.333550,57.5417,9.625689,668,4026,4694
229,230,18-08-2018,3,0,8,0,6,0,1,29.178347,33.112900,65.4583,15.624936,639,3166,3805
230,231,19-08-2018,3,0,8,0,0,0,2,28.085000,31.661050,72.2917,9.333636,797,3356,4153
231,232,20-08-2018,3,0,8,0,1,1,1,28.597500,32.449800,67.4167,6.999289,1914,3277,5191
232,233,21-08-2018,3,0,8,0,2,1,1,29.144153,33.776250,77.0000,16.666518,1249,2624,3873
233,234,22-08-2018,3,0,8,0,3,1,1,28.358347,31.912700,47.0000,18.542250,833,3925,4758
234,235,23-08-2018,3,0,8,0,4,1,1,26.274153,30.303350,45.5417,9.833121,1281,4614,5895
235,236,24-08-2018,3,0,8,0,5,1,1,27.606653,31.534600,60.5000,16.958236,949,4181,5130
236,237,25-08-2018,3,0,8,0,6,0,2,28.050847,32.292700,77.1667,14.125811,435,3107,3542
237,238,26-08-2018,3,0,8,0,0,0,1,28.700000,32.986650,76.1250,5.625488,768,3893,4661

In [8]:
df.shape #---> No. of rows No. of columns

(730, 16)

In [9]:
df.columns # --->Return list of all the columns present in the data

Index(['instant', 'dteday', 'season', 'yr', 'mnth', 'holiday', 'weekday',
       'workingday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed',
       'casual', 'registered', 'cnt'],
      dtype='object')

In [10]:
## Information summary of the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 730 entries, 0 to 729
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   instant     730 non-null    int64
 1   dteday      730 non-null    object
 2   season      730 non-null    int64
 3   yr          730 non-null    int64
 4   mnth        730 non-null    int64
 5   holiday     730 non-null    int64
 6   weekday     730 non-null    int64
 7   workingday  730 non-null    int64
 8   weathersit  730 non-null    int64
 9   temp        730 non-null    float64
 10  atemp       730 non-null    float64
 11  hum         730 non-null    float64
 12  windspeed   730 non-null    float64
 13  casual      730 non-null    int64
 14  registered  730 non-null    int64
 15  cnt         730 non-null    int64
dtypes: float64(4), int64(11), object(1)
memory usage: 91.4+ KB

In [11]:
# ther are few attribute so they dont have () example df.columns But function need to use ()  example df.info()

In [12]:
#Fetch one Column from the data frame, this method only works if space is not ther in column
df.temp

0      14.110847
1      14.902598
2       8.050924
3       8.200000
4       9.305237
5       8.378268
6       8.057402
7       6.765000
8       5.671653
9       6.184153
10      6.932731
11      7.081807
12      6.765000
13      6.595670
14      9.566653
15      9.498347
16      7.209153
17      8.883347
18     11.979134
19     10.728347
20      7.277500
21      2.424346
22      3.957390
23      3.993043
24      9.162598
25      8.917500
26      7.995000
27      8.342598
28      8.057402
29      8.877402
30      7.414153
31      7.879134
32     10.660000
33      7.665237
34      8.663464
35      9.566653
36     11.719153
37     11.138347
38      9.054153
39      5.526103
40      5.918268
41      7.752731
42      9.122500
43     12.977402
44     17.015000
45     10.909567
46     13.048701
47     17.869153
48     21.388347
49     16.365847
50     11.693897
51     12.436653
52      7.471102
53      9.091299
54     12.121732
55     14.938268
56     11.582500
57     14.082598
58     16.698193
59     10.933347
60     13.735000
61      8.131653
62     10.728347
63     15.750847
64     15.437402
65     10.731299
66     11.992500
67     12.129153
68     15.952731
69     12.977402
70     13.495847
71     15.758268
72     13.333897
73     13.013031
74     14.973897
75     17.015000
76     22.140000
77     19.372500
78     13.632500
79     17.647835
80     18.108347
81     14.225237
82     11.685000
83     10.830847
84     10.899153
85     10.374763
86     10.838268
87     12.402500
88     12.300000
89     11.001653
90     12.300000
91     12.915000
92     15.511653
93     23.506653
94     16.980847
95     16.024153
96     17.937500
97     13.769153
98     14.042500
99     17.493347
100    24.421732
101    20.602500
102    16.912500
103    19.167500
104    18.313347
105    17.664153
106    18.723347
107    21.012500
108    20.739153
109    24.395000
110    18.825847
111    13.803347
112    18.860000
113    23.848347
114    24.873347
115    25.898347
116    25.420000
117    25.317500
118    20.910000
119    19.372500
120    18.518347
121    22.515847
122    25.283347
123    16.980847
124    18.825847
125    19.645847
126    21.320000
127    21.661653
128    21.832500
129    21.832500
130    22.242500
131    21.935000
132    21.012500
133    21.354153
134    23.062500
135    23.677500
136    23.028347
137    22.550000
138    21.764153
139    22.003347
140    24.702500
141    24.770847
142    25.898347
143    27.060000
144    27.094153
145    29.041653
146    27.948347
147    26.889153
148    27.367500
149    30.066653
150    31.775000
151    31.330847
152    29.315000
153    25.420000
154    26.035000
155    26.581653
156    27.811653
157    29.007500
158    31.809153
159    33.141653
160    30.955000
161    29.725000
162    28.392500
163    26.035000
164    24.770847
165    25.693347
166    25.761653
167    26.615847
168    28.563347
169    28.665847
170    26.035000
171    27.914153
172    30.066653
173    29.861653
174    29.690847
175    28.495000
176    27.880000
177    27.982500
178    30.510847
179    29.861653
180    28.563347
181    29.622500
182    30.271653
183    29.383347
184    29.793347
185    30.613347
186    29.520000
187    30.750000
188    29.075847
189    30.066653
190    30.647500
191    31.262500
192    32.560847
193    30.613347
194    27.914153
195    27.196653
196    28.153347
197    29.485847
198    30.613347
199    31.843347
200    31.501653
201    33.415000
202    34.781653
203    34.815847
204    34.030000
205    30.476653
206    31.638347
207    31.775000
208    31.945847
209    34.371653
210    32.970847
211    33.039153
212    31.638347
213    32.116653
214    29.998347
215    29.110000
216    29.144153
217    29.383347
218    30.442500
219    31.365000
220    31.775000
221    31.433347
222    29.417500
223    29.041653
224    28.119153
225    27.743347
226    27.299153
227    28.734153
228    29.656653
229    29.178347
230    28.085000
231    28.597500
232    29.144153
233    28.358347
234    26.274153
235    27.606653
236    28.050847
237    28.700000
238    27.880000
239    28.989419
240    26.103347
241    26.205847
242    26.923347
243    26.855000
244    26.376653
245    27.435847
246    29.075847
247    27.606653
248    22.140000
249    24.565847
250    25.990433
251    26.650000
252    27.060000
253    26.786653
254    26.418268
255    26.684153
256    27.606653
257    23.677500
258    19.235847
259    20.158347
260    20.807500
261    22.515847
262    23.028347
263    24.395000
264    25.761653
265    24.975847
266    24.873347
267    26.000847
268    26.615847
269    26.103347
270    26.035000
271    25.283347
272    23.130847
273    16.810000
274    14.623347
275    15.750847
276    19.850847
277    22.071653
278    20.260847
279    20.944153
280    21.388347
281    22.174153
282    23.404153
283    23.233347
284    22.276653
285    24.155847
286    22.584153
287    20.773347
288    20.978347
289    21.900847
290    21.832500
291    22.211299
292    19.509153
293    17.527500
294    17.322500
295    17.288347
296    18.996653
297    19.338347
298    19.850847
299    19.270000
300    13.564153
301    10.420847
302    13.085847
303    13.940000
304    16.434153
305    15.477500
306    16.741653
307    16.536653
308    13.393347
309    14.281653
310    16.195000
311    16.741653
312    16.400000
313    15.580000
314    13.290847
315    14.623347
316    18.074153
317    21.730000
318    21.730000
319    18.723347
320    14.008347
321    11.240847
322    13.495847
323    18.996653
324    18.347500
325    17.083347
326    18.074153
327    15.306653
328    15.375000
329    15.409153
330    18.825847
331    20.642598
332    18.791653
333    13.325000
334    12.812500
335    12.880847
336    12.265847
337    13.564153
338    15.819153
339    18.962500
340    16.810000
341    10.899153
342    11.924153
343    11.275000
344     9.054153
345     9.771653
346    11.582500
347    13.017500
348    17.322500
349    15.375000
350    10.591653
351     9.771653
352    11.343347
353    15.819153
354    17.561653
355    17.356653
356    15.306653
357    12.402500
358    11.266103
359    13.191299
360    13.325000
361    12.264330
362    10.181653
363    12.778347
364    16.810000
365    15.170000
366    11.194763
367     6.150000
368     4.407500
369    10.899153
370    13.700847
371    16.126653
372    13.837500
373     9.190847
374    12.656536
375    11.240847
376    15.682500
377    11.240847
378     7.380000
379     6.833347
380     7.790000
381    15.294763
382    12.436653
383     7.790000
384     8.917500
385     7.106653
386     6.662500
387     8.951653
388    14.042500
389    12.060847
390    14.008347
391    17.425000
392    12.949153
393    11.582500
394    11.035847
395    15.990000
396    19.235847
397    16.365847
398    12.846653
399    10.830847
400    10.899153
401    11.586969
402    14.520847
403    10.523347
404    10.865000
405    11.514153
406     9.190847
407     5.227500
408     9.122500
409    13.085847
410    14.281653
411    12.983347
412    14.076653
413    14.213347
414    11.480000
415    11.480000
416    11.800866
417    16.229153
418    18.620847
419    16.707500
420    11.924153
421    11.445847
422    15.033347
423    14.725847
424    19.919153
425    14.486653
426    16.980847
427    13.359153
428     9.976653
429    10.591653
430    16.570847
431    21.627500
432    16.844153
433    11.787500
434    14.831299
435    19.133347
436    23.165000
437    23.472500
438    22.857500
439    17.869153
440    21.080847
441    19.372500
442    22.345000
443    22.994153
444    21.798347
445    22.720847
446    24.668347
447    20.602500
448    17.937500
449    18.279153
450    13.256653
451    19.850847
452    20.260847
453    15.170000
454    17.390847
455    17.459153
456    17.790433
457    19.133347
458    22.208347
459    17.835000
460    16.536653
461    17.937500
462    20.500000
463    20.055847
464    18.313347
465    14.296536
466    16.297500
467    18.142500
468    20.295000
469    24.873347
470    27.230847
471    24.941653
472    18.996653
473    20.431653
474    21.593347
475    23.370000
476    16.263347
477    13.188347
478    16.946653
479    19.543347
480    20.431653
481    18.757500
482    15.443347
483    18.791653
484    19.030847
485    25.146653
486    23.130847
487    22.960000
488    25.727500
489    25.488347
490    23.062500
491    22.037500
492    23.848347
493    23.575000
494    20.739153
495    21.866653
496    23.130847
497    25.112500
498    23.506653
499    25.078347
500    26.103347
501    24.326653
502    23.130847
503    24.600000
504    25.454153
505    24.531653
506    25.215000
507    25.488347
508    26.855000
509    27.880000
510    28.392500
511    28.290000
512    29.212500
513    29.622500
514    26.923347
515    27.880000
516    26.820847
517    23.916653
518    24.702500
519    24.497500
520    22.174153
521    22.720847
522    24.702500
523    26.615847
524    29.144153
525    29.793347
526    29.554153
527    26.786653
528    26.889153
529    26.581653
530    26.205847
531    25.898347
532    24.292500
533    23.301653
534    28.221653
535    32.082500
536    33.039153
537    31.877500
538    29.998347
539    30.476653
540    29.349153
541    25.864153
542    28.597500
543    30.715847
544    34.200847
545    31.365000
546    33.449153
547    32.048347
548    32.014153
549    32.355847
550    33.927500
551    33.961653
552    35.328347
553    33.722500
554    29.144153
555    29.554153
556    29.383347
557    29.349153
558    29.998347
559    28.836653
560    30.579153
561    31.296653
562    33.551653
563    32.526653
564    31.570000
565    27.299153
566    24.429153
567    27.367500
568    30.408347
569    30.784153
570    29.690847
571    31.843347
572    32.048347
573    30.989153
574    29.588347
575    29.964153
576    29.246653
577    29.417500
578    30.852500
579    31.399153
580    32.526653
581    31.535847
582    30.852500
583    30.169153
584    30.750000
585    30.989153
586    29.349153
587    28.392500
588    28.734153
589    29.554153
590    29.793347
591    28.973347
592    29.485847
593    29.656653
594    27.811653
595    26.069153
596    26.069153
597    26.615847
598    27.367500
599    28.529153
600    28.802500
601    27.128347
602    26.786653
603    28.836653
604    29.861653
605    28.085000
606    28.973347
607    31.330847
608    30.886653
609    28.563347
610    29.007500
611    29.759153
612    30.203347
613    28.563347
614    28.836653
615    27.025847
616    25.010000
617    23.916653
618    23.677500
619    24.565847
620    25.112500
621    25.966653
622    24.941653
623    23.780000
624    23.814153
625    25.556653
626    22.652500
627    22.413347
628    24.565847
629    26.650000
630    21.695847
631    21.080847
632    22.550000
633    26.035000
634    26.650000
635    25.385847
636    22.242500
637    21.593347
638    21.354153
639    24.224153
640    26.957500
641    26.957500
642    25.215000
643    22.720847
644    17.049153
645    15.716653
646    18.313347
647    21.080847
648    17.835000
649    17.937500
650    16.126653
651    21.388347
652    23.028347
653    19.201653
654    18.689153
655    21.422500
656    23.096653
657    19.850847
658    19.030847
659    19.987500
660    22.310847
661    24.087500
662    22.550000
663    22.379153
664    21.730000
665    19.577500
666    18.040000
667    13.045462
668    14.657500
669    14.999153
670    14.555000
671    14.076653
672    13.359153
673    13.085847
674    11.514153
675    12.129153
676    14.439134
677    14.828347
678    15.955847
679    17.254153
680    19.885000
681    14.076653
682    11.855847
683    13.188347
684    14.145000
685    13.325000
686    14.042500
687    15.614153
688    15.340847
689    14.486653
690    13.940000
691    15.101653
692    11.411653
693    10.079153
694    12.846653
695    11.958347
696    12.163347
697    11.515670
698    12.231653
699    12.231653
700    14.247500
701    18.552500
702    19.509153
703    17.971653
704    10.489153
705    13.154153
706    15.648347
707    15.750847
708    17.869153
709    14.486653
710    12.197500
711    12.129153
712    11.548347
713    13.290847
714    14.862500
715    16.126653
716    16.844153
717    13.632500
718    13.530000
719    13.393347
720    10.899153
721    10.079153
722     9.483464
723    11.943464
724     9.976653
725    10.420847
726    10.386653
727    10.386653
728    10.489153
729     8.849153
Name: temp, dtype: float64

In [13]:
df["temp"] # this method works when space is ther in column name

0      14.110847
1      14.902598
2       8.050924
3       8.200000
4       9.305237
5       8.378268
6       8.057402
7       6.765000
8       5.671653
9       6.184153
10      6.932731
11      7.081807
12      6.765000
13      6.595670
14      9.566653
15      9.498347
16      7.209153
17      8.883347
18     11.979134
19     10.728347
20      7.277500
21      2.424346
22      3.957390
23      3.993043
24      9.162598
25      8.917500
26      7.995000
27      8.342598
28      8.057402
29      8.877402
30      7.414153
31      7.879134
32     10.660000
33      7.665237
34      8.663464
35      9.566653
36     11.719153
37     11.138347
38      9.054153
39      5.526103
40      5.918268
41      7.752731
42      9.122500
43     12.977402
44     17.015000
45     10.909567
46     13.048701
47     17.869153
48     21.388347
49     16.365847
50     11.693897
51     12.436653
52      7.471102
53      9.091299
54     12.121732
55     14.938268
56     11.582500
57     14.082598
58     16.698193
59     10.933347
60     13.735000
61      8.131653
62     10.728347
63     15.750847
64     15.437402
65     10.731299
66     11.992500
67     12.129153
68     15.952731
69     12.977402
70     13.495847
71     15.758268
72     13.333897
73     13.013031
74     14.973897
75     17.015000
76     22.140000
77     19.372500
78     13.632500
79     17.647835
80     18.108347
81     14.225237
82     11.685000
83     10.830847
84     10.899153
85     10.374763
86     10.838268
87     12.402500
88     12.300000
89     11.001653
90     12.300000
91     12.915000
92     15.511653
93     23.506653
94     16.980847
95     16.024153
96     17.937500
97     13.769153
98     14.042500
99     17.493347
100    24.421732
101    20.602500
102    16.912500
103    19.167500
104    18.313347
105    17.664153
106    18.723347
107    21.012500
108    20.739153
109    24.395000
110    18.825847
111    13.803347
112    18.860000
113    23.848347
114    24.873347
115    25.898347
116    25.420000
117    25.317500
118    20.910000
119    19.372500
120    18.518347
121    22.515847
122    25.283347
123    16.980847
124    18.825847
125    19.645847
126    21.320000
127    21.661653
128    21.832500
129    21.832500
130    22.242500
131    21.935000
132    21.012500
133    21.354153
134    23.062500
135    23.677500
136    23.028347
137    22.550000
138    21.764153
139    22.003347
140    24.702500
141    24.770847
142    25.898347
143    27.060000
144    27.094153
145    29.041653
146    27.948347
147    26.889153
148    27.367500
149    30.066653
150    31.775000
151    31.330847
152    29.315000
153    25.420000
154    26.035000
155    26.581653
156    27.811653
157    29.007500
158    31.809153
159    33.141653
160    30.955000
161    29.725000
162    28.392500
163    26.035000
164    24.770847
165    25.693347
166    25.761653
167    26.615847
168    28.563347
169    28.665847
170    26.035000
171    27.914153
172    30.066653
173    29.861653
174    29.690847
175    28.495000
176    27.880000
177    27.982500
178    30.510847
179    29.861653
180    28.563347
181    29.622500
182    30.271653
183    29.383347
184    29.793347
185    30.613347
186    29.520000
187    30.750000
188    29.075847
189    30.066653
190    30.647500
191    31.262500
192    32.560847
193    30.613347
194    27.914153
195    27.196653
196    28.153347
197    29.485847
198    30.613347
199    31.843347
200    31.501653
201    33.415000
202    34.781653
203    34.815847
204    34.030000
205    30.476653
206    31.638347
207    31.775000
208    31.945847
209    34.371653
210    32.970847
211    33.039153
212    31.638347
213    32.116653
214    29.998347
215    29.110000
216    29.144153
217    29.383347
218    30.442500
219    31.365000
220    31.775000
221    31.433347
222    29.417500
223    29.041653
224    28.119153
225    27.743347
226    27.299153
227    28.734153
228    29.656653
229    29.178347
230    28.085000
231    28.597500
232    29.144153
233    28.358347
234    26.274153
235    27.606653
236    28.050847
237    28.700000
238    27.880000
239    28.989419
240    26.103347
241    26.205847
242    26.923347
243    26.855000
244    26.376653
245    27.435847
246    29.075847
247    27.606653
248    22.140000
249    24.565847
250    25.990433
251    26.650000
252    27.060000
253    26.786653
254    26.418268
255    26.684153
256    27.606653
257    23.677500
258    19.235847
259    20.158347
260    20.807500
261    22.515847
262    23.028347
263    24.395000
264    25.761653
265    24.975847
266    24.873347
267    26.000847
268    26.615847
269    26.103347
270    26.035000
271    25.283347
272    23.130847
273    16.810000
274    14.623347
275    15.750847
276    19.850847
277    22.071653
278    20.260847
279    20.944153
280    21.388347
281    22.174153
282    23.404153
283    23.233347
284    22.276653
285    24.155847
286    22.584153
287    20.773347
288    20.978347
289    21.900847
290    21.832500
291    22.211299
292    19.509153
293    17.527500
294    17.322500
295    17.288347
296    18.996653
297    19.338347
298    19.850847
299    19.270000
300    13.564153
301    10.420847
302    13.085847
303    13.940000
304    16.434153
305    15.477500
306    16.741653
307    16.536653
308    13.393347
309    14.281653
310    16.195000
311    16.741653
312    16.400000
313    15.580000
314    13.290847
315    14.623347
316    18.074153
317    21.730000
318    21.730000
319    18.723347
320    14.008347
321    11.240847
322    13.495847
323    18.996653
324    18.347500
325    17.083347
326    18.074153
327    15.306653
328    15.375000
329    15.409153
330    18.825847
331    20.642598
332    18.791653
333    13.325000
334    12.812500
335    12.880847
336    12.265847
337    13.564153
338    15.819153
339    18.962500
340    16.810000
341    10.899153
342    11.924153
343    11.275000
344     9.054153
345     9.771653
346    11.582500
347    13.017500
348    17.322500
349    15.375000
350    10.591653
351     9.771653
352    11.343347
353    15.819153
354    17.561653
355    17.356653
356    15.306653
357    12.402500
358    11.266103
359    13.191299
360    13.325000
361    12.264330
362    10.181653
363    12.778347
364    16.810000
365    15.170000
366    11.194763
367     6.150000
368     4.407500
369    10.899153
370    13.700847
371    16.126653
372    13.837500
373     9.190847
374    12.656536
375    11.240847
376    15.682500
377    11.240847
378     7.380000
379     6.833347
380     7.790000
381    15.294763
382    12.436653
383     7.790000
384     8.917500
385     7.106653
386     6.662500
387     8.951653
388    14.042500
389    12.060847
390    14.008347
391    17.425000
392    12.949153
393    11.582500
394    11.035847
395    15.990000
396    19.235847
397    16.365847
398    12.846653
399    10.830847
400    10.899153
401    11.586969
402    14.520847
403    10.523347
404    10.865000
405    11.514153
406     9.190847
407     5.227500
408     9.122500
409    13.085847
410    14.281653
411    12.983347
412    14.076653
413    14.213347
414    11.480000
415    11.480000
416    11.800866
417    16.229153
418    18.620847
419    16.707500
420    11.924153
421    11.445847
422    15.033347
423    14.725847
424    19.919153
425    14.486653
426    16.980847
427    13.359153
428     9.976653
429    10.591653
430    16.570847
431    21.627500
432    16.844153
433    11.787500
434    14.831299
435    19.133347
436    23.165000
437    23.472500
438    22.857500
439    17.869153
440    21.080847
441    19.372500
442    22.345000
443    22.994153
444    21.798347
445    22.720847
446    24.668347
447    20.602500
448    17.937500
449    18.279153
450    13.256653
451    19.850847
452    20.260847
453    15.170000
454    17.390847
455    17.459153
456    17.790433
457    19.133347
458    22.208347
459    17.835000
460    16.536653
461    17.937500
462    20.500000
463    20.055847
464    18.313347
465    14.296536
466    16.297500
467    18.142500
468    20.295000
469    24.873347
470    27.230847
471    24.941653
472    18.996653
473    20.431653
474    21.593347
475    23.370000
476    16.263347
477    13.188347
478    16.946653
479    19.543347
480    20.431653
481    18.757500
482    15.443347
483    18.791653
484    19.030847
485    25.146653
486    23.130847
487    22.960000
488    25.727500
489    25.488347
490    23.062500
491    22.037500
492    23.848347
493    23.575000
494    20.739153
495    21.866653
496    23.130847
497    25.112500
498    23.506653
499    25.078347
500    26.103347
501    24.326653
502    23.130847
503    24.600000
504    25.454153
505    24.531653
506    25.215000
507    25.488347
508    26.855000
509    27.880000
510    28.392500
511    28.290000
512    29.212500
513    29.622500
514    26.923347
515    27.880000
516    26.820847
517    23.916653
518    24.702500
519    24.497500
520    22.174153
521    22.720847
522    24.702500
523    26.615847
524    29.144153
525    29.793347
526    29.554153
527    26.786653
528    26.889153
529    26.581653
530    26.205847
531    25.898347
532    24.292500
533    23.301653
534    28.221653
535    32.082500
536    33.039153
537    31.877500
538    29.998347
539    30.476653
540    29.349153
541    25.864153
542    28.597500
543    30.715847
544    34.200847
545    31.365000
546    33.449153
547    32.048347
548    32.014153
549    32.355847
550    33.927500
551    33.961653
552    35.328347
553    33.722500
554    29.144153
555    29.554153
556    29.383347
557    29.349153
558    29.998347
559    28.836653
560    30.579153
561    31.296653
562    33.551653
563    32.526653
564    31.570000
565    27.299153
566    24.429153
567    27.367500
568    30.408347
569    30.784153
570    29.690847
571    31.843347
572    32.048347
573    30.989153
574    29.588347
575    29.964153
576    29.246653
577    29.417500
578    30.852500
579    31.399153
580    32.526653
581    31.535847
582    30.852500
583    30.169153
584    30.750000
585    30.989153
586    29.349153
587    28.392500
588    28.734153
589    29.554153
590    29.793347
591    28.973347
592    29.485847
593    29.656653
594    27.811653
595    26.069153
596    26.069153
597    26.615847
598    27.367500
599    28.529153
600    28.802500
601    27.128347
602    26.786653
603    28.836653
604    29.861653
605    28.085000
606    28.973347
607    31.330847
608    30.886653
609    28.563347
610    29.007500
611    29.759153
612    30.203347
613    28.563347
614    28.836653
615    27.025847
616    25.010000
617    23.916653
618    23.677500
619    24.565847
620    25.112500
621    25.966653
622    24.941653
623    23.780000
624    23.814153
625    25.556653
626    22.652500
627    22.413347
628    24.565847
629    26.650000
630    21.695847
631    21.080847
632    22.550000
633    26.035000
634    26.650000
635    25.385847
636    22.242500
637    21.593347
638    21.354153
639    24.224153
640    26.957500
641    26.957500
642    25.215000
643    22.720847
644    17.049153
645    15.716653
646    18.313347
647    21.080847
648    17.835000
649    17.937500
650    16.126653
651    21.388347
652    23.028347
653    19.201653
654    18.689153
655    21.422500
656    23.096653
657    19.850847
658    19.030847
659    19.987500
660    22.310847
661    24.087500
662    22.550000
663    22.379153
664    21.730000
665    19.577500
666    18.040000
667    13.045462
668    14.657500
669    14.999153
670    14.555000
671    14.076653
672    13.359153
673    13.085847
674    11.514153
675    12.129153
676    14.439134
677    14.828347
678    15.955847
679    17.254153
680    19.885000
681    14.076653
682    11.855847
683    13.188347
684    14.145000
685    13.325000
686    14.042500
687    15.614153
688    15.340847
689    14.486653
690    13.940000
691    15.101653
692    11.411653
693    10.079153
694    12.846653
695    11.958347
696    12.163347
697    11.515670
698    12.231653
699    12.231653
700    14.247500
701    18.552500
702    19.509153
703    17.971653
704    10.489153
705    13.154153
706    15.648347
707    15.750847
708    17.869153
709    14.486653
710    12.197500
711    12.129153
712    11.548347
713    13.290847
714    14.862500
715    16.126653
716    16.844153
717    13.632500
718    13.530000
719    13.393347
720    10.899153
721    10.079153
722     9.483464
723    11.943464
724     9.976653
725    10.420847
726    10.386653
727    10.386653
728    10.489153
729     8.849153
Name: temp, dtype: float64

In [14]:
##Fetch more than one column
df[["temp","hum","weathersit"]].head(5)
#[] ------> Indexing
#[]-------> List of columns

        temp      hum  weathersit
0  14.110847  80.5833           2
1  14.902598  69.6087           2
2   8.050924  43.7273           1
3   8.200000  59.0435           1
4   9.305237  43.6957           1

In [15]:
df[["temp","hum","weathersit"]].count()

temp          730
hum           730
weathersit    730
dtype: int64

In [16]:
# to check the count of values on any column
# It does not include nan or missiong values 
df["mnth"].count()

730

In [17]:
df.count()

instant       730
dteday        730
season        730
yr            730
mnth          730
holiday       730
weekday       730
workingday    730
weathersit    730
temp          730
atemp         730
hum           730
windspeed     730
casual        730
registered    730
cnt           730
dtype: int64

In [18]:
df["mnth"].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [19]:
df["mnth"].nunique()

12

In [20]:
df[["temp","hum","weathersit"]].nunique()

temp          498
hum           594
weathersit      3
dtype: int64

In [21]:
df.nunique()

instant       730
dteday        730
season          4
yr              2
mnth           12
holiday         2
weekday         7
workingday      2
weathersit      3
temp          498
atemp         689
hum           594
windspeed     649
casual        605
registered    678
cnt           695
dtype: int64

In [22]:
# Frequency count of unique values in any column
df["season"].value_counts()

season
3    188
2    184
1    180
4    178
Name: count, dtype: int64

In [23]:
#nunique ----> count of unique values in any column or complete data frame
#count ------> overall count of values in any column or complete dataframe
#unique -----> unique calue in any column
#values_counts---> frequency count of all unique values in any column

In [24]:
for i in ["mnth","season","yr","holiday"]:
    print("-----------------------",i,"-----------------------------")
    print(df[i].value_counts())
    print("Unique Values", df[i].unique())

----------------------- mnth -----------------------------
mnth
1     62
3     62
5     62
7     62
8     62
10    62
12    62
4     60
6     60
9     60
11    60
2     56
Name: count, dtype: int64
Unique Values [ 1  2  3  4  5  6  7  8  9 10 11 12]
----------------------- season -----------------------------
season
3    188
2    184
1    180
4    178
Name: count, dtype: int64
Unique Values [1 2 3 4]
----------------------- yr -----------------------------
yr
0    365
1    365
Name: count, dtype: int64
Unique Values [0 1]
----------------------- holiday -----------------------------
holiday
0    709
1     21
Name: count, dtype: int64
Unique Values [0 1]

In [25]:
#Statistical operations

In [26]:
df["temp"].max()

35.328347

In [27]:
df["temp"].idxmax()

552

In [28]:
df["temp"].min()

2.4243464

In [29]:
df["temp"].idxmin()

21

In [30]:
df["temp"].mean()

20.319259216986303

In [31]:
df["temp"].median()

20.4658265

In [32]:
df["temp"].std()

7.506728936951134

In [33]:
df["temp"].var()

56.35097933285951

In [34]:
round(df["temp"].var(),2)

56.35

In [35]:
#staticial summary of data
df.describe()

,instant,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
count,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000
mean,365.500000,2.498630,0.500000,6.526027,0.028767,2.995890,0.690411,1.394521,20.319259,23.726322,62.765175,12.763620,849.249315,3658.757534,4508.006849
std,210.877136,1.110184,0.500343,3.450215,0.167266,2.000339,0.462641,0.544807,7.506729,8.150308,14.237589,5.195841,686.479875,1559.758728,1936.011647
min,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,2.424346,3.953480,0.000000,1.500244,2.000000,20.000000,22.000000
25%,183.250000,2.000000,0.000000,4.000000,0.000000,1.000000,0.000000,1.000000,13.811885,16.889713,52.000000,9.041650,316.250000,2502.250000,3169.750000
50%,365.500000,3.000000,0.500000,7.000000,0.000000,3.000000,1.000000,1.000000,20.465826,24.368225,62.625000,12.125325,717.000000,3664.500000,4548.500000
75%,547.750000,3.000000,1.000000,10.000000,0.000000,5.000000,1.000000,2.000000,26.880615,30.445775,72.989575,15.625589,1096.500000,4783.250000,5966.000000
max,730.000000,4.000000,1.000000,12.000000,1.000000,6.000000,1.000000,3.000000,35.328347,42.044800,97.250000,34.000021,3410.000000,6946.000000,8714.000000

In [36]:
df[["holiday","temp"]].describe()

          holiday        temp
count  730.000000  730.000000
mean     0.028767   20.319259
std      0.167266    7.506729
min      0.000000    2.424346
25%      0.000000   13.811885
50%      0.000000   20.465826
75%      0.000000   26.880615
max      1.000000   35.328347

In [37]:
df[["holiday","temp"]].describe().T[["max","min"]]
#T transpose

               max       min
holiday   1.000000  0.000000
temp     35.328347  2.424346

In [38]:
#how can we filter data from dataframe
#I want to filter data greter temp greter than 32
df[df["temp"]>34]

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
202,203,22-07-2018,3,0,7,0,0,0,1,34.781653,42.04480,58.0417,8.917700,562,2825,3387
203,204,23-07-2018,3,0,7,0,1,1,1,34.815847,40.21435,50.0000,8.791807,987,2298,3285
204,205,24-07-2018,3,0,7,0,2,1,1,34.030000,39.74145,55.0833,11.334457,1050,2556,3606
209,210,29-07-2018,3,0,7,0,0,0,1,34.371653,39.29835,54.2500,11.667246,670,3176,3846
544,545,29-06-2019,3,1,6,0,6,0,1,34.200847,39.33065,48.8750,11.082939,829,4634,5463
552,553,07-07-2019,3,1,7,0,0,0,1,35.328347,40.24565,49.2083,10.958118,1448,3392,4840

In [39]:
#&------->and secound condution
df[(df["temp"]> 34) & (df["yr"]==1)]

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
544,545,29-06-2019,3,1,6,0,6,0,1,34.200847,39.33065,48.8750,11.082939,829,4634,5463
552,553,07-07-2019,3,1,7,0,0,0,1,35.328347,40.24565,49.2083,10.958118,1448,3392,4840

In [40]:
# | ------> or condition
df[(df["temp"]>34) | (df["yr"]==1)]

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
202,203,22-07-2018,3,0,7,0,0,0,1,34.781653,42.04480,58.0417,8.917700,562,2825,3387
203,204,23-07-2018,3,0,7,0,1,1,1,34.815847,40.21435,50.0000,8.791807,987,2298,3285
204,205,24-07-2018,3,0,7,0,2,1,1,34.030000,39.74145,55.0833,11.334457,1050,2556,3606
209,210,29-07-2018,3,0,7,0,0,0,1,34.371653,39.29835,54.2500,11.667246,670,3176,3846
365,366,01-01-2019,1,1,1,0,2,1,1,15.170000,18.78105,69.2500,12.875189,686,1608,2294
366,367,02-01-2019,1,1,1,1,3,0,1,11.194763,12.61520,38.1304,22.087555,244,1707,1951
367,368,03-01-2019,1,1,1,0,4,1,1,6.150000,6.31375,44.1250,24.499957,89,2147,2236
368,369,04-01-2019,1,1,1,0,5,1,2,4.407500,5.96685,41.4583,12.374900,95,2273,2368
369,370,05-01-2019,1,1,1,0,6,0,1,10.899153,13.92060,52.4167,8.709129,140,3132,3272
370,371,06-01-2019,1,1,1,0,0,0,1,13.700847,17.01335,54.2083,11.249836,307,3791,4098
371,372,07-01-2019,1,1,1,0,1,1,1,16.126653,19.53895,53.1667,11.708786,1070,3451,4521
372,373,08-01-2019,1,1,1,0,2,1,1,13.837500,17.01290,46.5000,12.833314,599,2826,3425
373,374,09-01-2019,1,1,1,0,3,1,2,9.190847,12.37395,70.1667,6.626300,106,2270,2376
374,375,10-01-2019,1,1,1,0,4,1,1,12.656536,15.94130,64.6522,12.565984,173,3425,3598
375,376,11-01-2019,1,1,1,0,5,1,2,11.240847,14.14105,84.7500,8.791807,92,2085,2177
376,377,12-01-2019,1,1,1,0,6,0,2,15.682500,19.09690,80.2917,12.124789,269,3828,4097
377,378,13-01-2019,1,1,1,0,0,0,1,11.240847,12.46810,50.7500,25.333236,174,3040,3214
378,379,14-01-2019,1,1,1,0,1,1,1,7.380000,9.15435,45.7500,12.541261,333,2160,2493
379,380,15-01-2019,1,1,1,0,2,1,1,6.833347,8.08125,41.9167,16.834286,284,2027,2311
380,381,16-01-2019,1,1,1,1,3,0,1,7.790000,9.53315,52.2500,15.500986,217,2081,2298
381,382,17-01-2019,1,1,1,0,4,1,2,15.294763,18.21390,71.6087,23.391710,127,2808,2935
382,383,18-01-2019,1,1,1,0,5,1,1,12.436653,13.76270,44.3333,27.833743,109,3267,3376
383,384,19-01-2019,1,1,1,0,6,0,1,7.790000,9.50190,49.7500,14.750586,130,3162,3292
384,385,20-01-2019,1,1,1,0,0,0,2,8.917500,11.04790,45.0000,13.584250,115,3048,3163
385,386,21-01-2019,1,1,1,0,1,1,2,7.106653,8.74375,83.1250,14.917014,67,1234,1301
386,387,22-01-2019,1,1,1,0,2,1,2,6.662500,8.11250,79.6250,13.375746,196,1781,1977
387,388,23-01-2019,1,1,1,0,3,1,2,8.951653,12.15290,91.1250,7.417436,145,2287,2432
388,389,24-01-2019,1,1,1,0,4,1,1,14.042500,17.45540,83.5833,8.292389,439,3900,4339
389,390,25-01-2019,1,1,1,0,5,1,1,12.060847,14.74105,64.3750,10.791757,467,3803,4270
390,391,26-01-2019,1,1,1,0,6,0,2,14.008347,17.80250,76.9583,4.917519,244,3831,4075
391,392,27-01-2019,1,1,1,0,0,0,2,17.425000,20.76915,74.1250,22.958689,269,3187,3456
392,393,28-01-2019,1,1,1,0,1,1,1,12.949153,16.31895,54.3333,14.125543,775,3248,4023
393,394,29-01-2019,1,1,1,0,2,1,1,11.582500,13.63605,31.1250,16.083350,558,2685,3243
394,395,30-01-2019,1,1,1,0,3,1,1,11.035847,13.13125,40.0833,14.458064,126,3498,3624
395,396,31-01-2019,1,1,1,0,4,1,1,15.990000,19.06585,41.6667,17.541739,324,4185,4509
396,397,01-02-2019,1,1,2,0,5,1,1,19.235847,23.32690,50.7917,12.667489,304,4275,4579
397,398,02-02-2019,1,1,2,0,6,0,2,16.365847,19.94855,67.2917,12.541529,190,3571,3761
398,399,03-02-2019,1,1,2,0,0,0,1,12.846653,15.46730,52.6667,11.959232,310,3841,4151
399,400,04-02-2019,1,1,2,0,1,1,2,10.830847,13.63625,77.9583,8.167032,384,2448,2832
400,401,05-02-2019,1,1,2,0,2,1,2,10.899153,13.22605,68.7917,11.791732,318,2629,2947
401,402,06-02-2019,1,1,2,0,3,1,1,11.586969,14.82130,62.2174,10.304600,206,3578,3784
402,403,07-02-2019,1,1,2,0,4,1,1,14.520847,18.05520,49.6250,9.874393,199,4176,4375
403,404,08-02-2019,1,1,2,0,5,1,2,10.523347,13.32105,72.2917,8.959307,109,2693,2802
404,405,09-02-2019,1,1,2,0,6,0,1,10.865000,13.09940,56.2083,13.000479,163,3667,3830
405,406,10-02-2019,1,1,2,0,0,0,2,11.514153,14.67790,54.0000,7.834243,227,3604,3831
406,407,11-02-2019,1,1,2,0,1,1,3,9.190847,10.54335,73.1250,19.416332,192,1977,2169
407,408,12-02-2019,1,1,2,0,2,1,1,5.227500,5.08290,46.4583,27.417204,73,1456,1529
408,409,13-02-2019,1,1,2,0,3,1,1,9.122500,11.39565,41.1250,11.207961,94,3328,3422
409,410,14-02-2019,1,1,2,0,4,1,2,13.085847,16.69730,50.8750,9.458993,135,3787,3922
410,411,15-02-2019,1,1,2,0,5,1,1,14.281653,17.58145,53.1250,12.167200,141,4028,4169
411,412,16-02-2019,1,1,2,0,6,0,2,12.983347,16.50810,75.2917,6.125475,74,2931,3005
412,413,17-02-2019,1,1,2,0,0,0,1,14.076653,17.58145,63.4583,13.791682,349,3805,4154
413,414,18-02-2019,1,1,2,0,1,1,1,14.213347,17.77125,53.4583,12.792243,1435,2883,4318
414,415,19-02-2019,1,1,2,0,2,1,2,11.480000,13.28940,51.5833,16.958504,618,2071,2689
415,416,20-02-2019,1,1,2,1,3,0,1,11.480000,13.66955,50.7826,15.348561,502,2627,3129
416,417,21-02-2019,1,1,2,0,4,1,1,11.800866,14.75565,59.4348,13.783039,163,3614,3777
417,418,22-02-2019,1,1,2,0,5,1,1,16.229153,19.63335,56.7917,15.709557,394,4379,4773
418,419,23-02-2019,1,1,2,0,6,0,1,18.620847,22.22230,55.4583,12.791171,516,4546,5062
419,420,24-02-2019,1,1,2,0,0,0,2,16.707500,20.54855,73.7500,15.916989,246,3241,3487
420,421,25-02-2019,1,1,2,0,1,1,1,11.924153,12.78375,39.5833,28.250014,317,2415,2732
421,422,26-02-2019,1,1,2,0,2,1,1,11.445847,13.41540,41.0000,13.750343,515,2874,3389
422,423,27-02-2019,1,1,2,0,3,1,1,15.033347,17.89770,49.0833,17.958211,253,4069,4322
423,424,28-02-2019,1,1,2,0,4,1,1,14.725847,17.67625,39.5833,12.958939,229,4134,4363
424,425,01-03-2019,1,1,3,0,5,1,1,19.919153,23.76855,61.5417,15.208129,325,4665,4990
425,426,02-03-2019,1,1,3,0,6,0,2,14.486653,17.99210,65.7083,9.708568,246,2948,3194
426,427,03-03-2019,1,1,3,0,0,0,2,16.980847,20.67460,62.1250,10.792293,956,3110,4066
427,428,04-03-2019,1,1,3,0,1,1,1,13.359153,15.15105,40.3333,22.416257,710,2713,3423
428,429,05-03-2019,1,1,3,0,2,1,1,9.976653,12.05855,50.6250,15.333486,203,3130,3333
429,430,06-03-2019,1,1,3,0,3,1,1,10.591653,12.75210,45.6667,13.458625,221,3735,3956
430,431,07-03-2019,1,1,3,0,4,1,1,16.570847,19.25500,51.3333,23.167193,432,4484,4916
431,432,08-03-2019,1,1,3,0,5,1,1,21.627500,26.23020,56.7500,29.584721,486,4896,5382
432,433,09-03-2019,1,1,3,0,6,0,2,16.844153,19.85415,40.7083,27.791600,447,4122,4569
433,434,10-03-2019,1,1,3,0,0,0,1,11.787500,13.88835,35.0417,15.125250,968,3150,4118
434,435,11-03-2019,1,1,3,0,1,1,1,14.831299,17.98350,47.6957,14.913329,1658,3253,4911
435,436,12-03-2019,1,1,3,0,2,1,1,19.133347,22.97960,48.9167,13.916771,838,4460,5298
436,437,13-03-2019,1,1,3,0,3,1,1,23.165000,27.14645,61.7500,15.875650,762,5085,5847
437,438,14-03-2019,1,1,3,0,4,1,1,23.472500,27.43085,50.7083,7.709154,997,5315,6312
438,439,15-03-2019,1,1,3,0,5,1,1,22.857500,26.64125,57.9583,10.042161,1005,5187,6192
439,440,16-03-2019,1,1,3,0,6,0,2,17.869153,21.81145,84.2083,7.583864,548,3830,4378
440,441,17-03-2019,1,1,3,0,0,0,2,21.080847,25.25230,75.5833,7.417168,3155,4681,7836
441,442,18-03-2019,1,1,3,0,1,1,2,19.372500,23.20000,81.0000,8.501161,2207,3685,5892
442,443,19-03-2019,1,1,3,0,2,1,1,22.345000,26.64105,72.8750,10.875239,982,5171,6153
443,444,20-03-2019,1,1,3,0,3,1,1,22.994153,26.92665,80.7917,8.125157,1051,5042,6093
444,445,21-03-2019,2,1,3,0,4,1,2,21.798347,25.66290,82.1250,6.000406,1122,5108,6230
445,446,22-03-2019,2,1,3,0,5,1,1,22.720847,26.57835,83.1250,7.876654,1334,5537,6871
446,447,23-03-2019,2,1,3,0,6,0,2,24.668347,28.50335,69.4167,7.792100,2469,5893,8362
447,448,24-03-2019,2,1,3,0,0,0,2,20.602500,24.33665,88.5417,12.916461,1033,2339,3372
448,449,25-03-2019,2,1,3,0,1,1,2,17.937500,21.87440,88.0833,14.791925,1532,3464,4996
449,450,26-03-2019,2,1,3,0,2,1,1,18.279153,21.93750,47.7917,25.917007,795,4763,5558
450,451,27-03-2019,2,1,3,0,3,1,1,13.256653,15.78270,29.0000,12.541864,531,4571,5102
451,452,28-03-2019,2,1,3,0,4,1,1,19.850847,23.54750,48.1250,19.541957,674,5024,5698
452,453,29-03-2019,2,1,3,0,5,1,1,20.260847,24.11520,43.9167,21.416550,834,5299,6133
453,454,30-03-2019,2,1,3,0,6,0,2,15.170000,18.78105,58.0833,9.250489,796,4663,5459
454,455,31-03-2019,2,1,3,0,0,0,2,17.390847,21.08540,73.8333,16.791339,2301,3934,6235
455,456,01-04-2019,2,1,4,0,1,1,2,17.459153,20.86435,67.6250,11.541889,2347,3694,6041
456,457,02-04-2019,2,1,4,0,2,1,1,17.790433,21.37565,50.4348,20.913313,1208,4728,5936
457,458,03-04-2019,2,1,4,0,3,1,1,19.133347,23.07415,39.6667,6.708911,1348,5424,6772
458,459,04-04-2019,2,1,4,0,4,1,1,22.208347,26.67250,46.9583,12.125325,1058,5378,6436
459,460,05-04-2019,2,1,4,0,5,1,1,17.835000,21.55815,37.4167,14.708443,1192,5265,6457
460,461,06-04-2019,2,1,4,0,6,0,1,16.536653,19.53835,37.7083,20.125996,1807,4653,6460
461,462,07-04-2019,2,1,4,0,0,0,1,17.937500,21.30645,25.4167,18.416357,3252,3605,6857
462,463,08-04-2019,2,1,4,0,1,1,1,20.500000,24.62125,27.5833,15.583932,2230,2939,5169
463,464,09-04-2019,2,1,4,0,2,1,1,20.055847,23.83190,31.7500,23.999132,905,4680,5585
464,465,10-04-2019,2,1,4,0,3,1,1,18.313347,21.81165,43.5000,16.708125,819,5099,5918
465,466,11-04-2019,2,1,4,0,4,1,1,14.296536,16.86370,46.9565,19.783358,482,4380,4862
466,467,12-04-2019,2,1,4,0,5,1,1,16.297500,19.38020,46.6250,19.458743,663,4746,5409
467,468,13-04-2019,2,1,4,0,6,0,1,18.142500,21.59040,40.8333,10.416557,1252,5146,6398
468,469,14-04-2019,2,1,4,0,0,0,1,20.295000,24.39980,50.2917,12.791439,2795,4665,7460
469,470,15-04-2019,2,1,4,0,1,1,1,24.873347,28.69375,50.7917,15.083643,2846,4286,7132
470,471,16-04-2019,2,1,4,1,2,0,1,27.230847,30.74625,56.1667,19.083543,1198,5172,6370
471,472,17-04-2019,2,1,4,0,3,1,1,24.941653,29.92435,39.0417,18.333143,989,5702,6691
472,473,18-04-2019,2,1,4,0,4,1,2,18.996653,22.85190,56.9167,11.250104,347,4020,4367
473,474,19-04-2019,2,1,4,0,5,1,1,20.431653,24.65230,61.2500,4.417256,846,5719,6565
474,475,20-04-2019,2,1,4,0,6,0,1,21.593347,25.78875,69.4583,10.041357,1340,5950,7290
475,476,21-04-2019,2,1,4,0,0,0,1,23.370000,27.14605,68.2917,19.000329,2541,4083,6624
476,477,22-04-2019,2,1,4,0,1,1,3,16.263347,19.47520,83.5417,23.084582,120,907,1027
477,478,23-04-2019,2,1,4,0,2,1,2,13.188347,15.05625,76.6667,20.334232,195,3019,3214
478,479,24-04-2019,2,1,4,0,3,1,1,16.946653,20.26415,45.4167,16.708661,518,5115,5633
479,480,25-04-2019,2,1,4,0,4,1,1,19.543347,23.51585,42.7917,7.959064,655,5541,6196
480,481,26-04-2019,2,1,4,0,5,1,2,20.431653,24.17915,75.6667,11.833875,475,4551,5026
481,482,27-04-2019,2,1,4,0,6,0,1,18.757500,22.63185,40.0833,23.291411,1014,5219,6233
482,483,28-04-2019,2,1,4,0,0,0,2,15.443347,18.87520,48.9583,8.708325,1120,3100,4220
483,484,29-04-2019,2,1,4,0,1,1,1,18.791653,22.50605,58.7083,7.832836,2229,4075,6304
484,485,30-04-2019,2,1,4,0,2,1,2,19.030847,22.88480,57.0000,11.499746,665,4907,5572
485,486,01-05-2019,2,1,5,0,3,1,2,25.146653,28.85105,65.9583,10.458432,653,5087,5740
486,487,02-05-2019,2,1,5,0,4,1,1,23.130847,26.89480,79.7083,9.249886,667,5502,6169
487,488,03-05-2019,2,1,5,0,5,1,2,22.960000,26.86210,76.8333,8.957632,764,5657,6421
488,489,04-05-2019,2,1,5,0,6,0,1,25.727500,29.54585,73.5417,10.916846,1069,5227,6296
489,490,05-05-2019,2,1,5,0,0,0,2,25.488347,29.23040,75.6667,10.250464,2496,4387,6883
490,491,06-05-2019,2,1,5,0,1,1,2,23.062500,27.33685,74.0000,10.041893,2135,4224,6359
491,492,07-05-2019,2,1,5,0,2,1,2,22.037500,26.35710,66.4167,15.458307,1008,5265,6273
492,493,08-05-2019,2,1,5,0,3,1,2,23.848347,27.87355,68.5833,19.833943,738,4990,5728
493,494,09-05-2019,2,1,5,0,4,1,2,23.575000,27.65125,74.4167,14.499604,620,4097,4717
494,495,10-05-2019,2,1,5,0,5,1,1,20.739153,24.58915,55.2083,21.042221,1026,5546,6572
495,496,11-05-2019,2,1,5,0,6,0,1,21.866653,26.04165,36.0417,15.874779,1319,5711,7030
496,497,12-05-2019,2,1,5,0,0,0,1,23.130847,27.24085,48.0417,8.249911,2622,4807,7429
497,498,13-05-2019,2,1,5,0,1,1,1,25.112500,29.26190,57.6250,15.082839,2172,3946,6118
498,499,14-05-2019,2,1,5,0,2,1,2,23.506653,27.49500,78.9583,14.250364,342,2501,2843
499,500,15-05-2019,2,1,5,0,3,1,2,25.078347,28.82020,79.4583,9.875264,625,4490,5115
500,501,16-05-2019,2,1,5,0,4,1,1,26.103347,29.79875,69.7917,8.208304,991,6433,7424
501,502,17-05-2019,2,1,5,0,5,1,1,24.326653,28.63065,52.0000,15.374825,1242,6142,7384
502,503,18-05-2019,2,1,5,0,6,0,1,23.130847,27.55605,52.3333,9.166739,1521,6118,7639
503,504,19-05-2019,2,1,5,0,0,0,1,24.600000,28.34540,45.6250,5.626325,3410,4884,8294
504,505,20-05-2019,2,1,5,0,1,1,1,25.454153,29.19835,53.0417,17.042589,2704,4425,7129
505,506,21-05-2019,2,1,5,0,2,1,2,24.531653,28.28335,81.1250,15.624668,630,3729,4359
506,507,22-05-2019,2,1,5,0,3,1,2,25.215000,29.04125,76.5833,7.917189,819,5254,6073
507,508,23-05-2019,2,1,5,0,4,1,2,25.488347,29.23060,77.4583,6.834000,766,4494,5260
508,509,24-05-2019,2,1,5,0,5,1,1,26.855000,30.33500,71.6667,11.584032,1059,5711,6770
509,510,25-05-2019,2,1,5,0,6,0,1,27.880000,31.37645,74.7083,9.416850,1417,5317,6734
510,511,26-05-2019,2,1,5,0,0,0,1,28.392500,32.13480,73.2500,13.332464,2855,3681,6536
511,512,27-05-2019,2,1,5,0,1,1,1,28.290000,32.07125,69.7083,14.416457,3283,3308,6591
512,513,28-05-2019,2,1,5,1,2,0,1,29.212500,33.96500,67.6250,13.166907,2557,3486,6043
513,514,29-05-2019,2,1,5,0,3,1,1,29.622500,33.64960,68.4583,19.791800,880,4863,5743
514,515,30-05-2019,2,1,5,0,4,1,2,26.923347,30.55645,67.0000,9.000043,745,6110,6855
515,516,31-05-2019,2,1,5,0,5,1,1,27.880000,31.56645,49.2917,13.083693,1100,6238,7338
516,517,01-06-2019,2,1,6,0,6,0,2,26.820847,30.39810,75.5417,15.916721,533,3594,4127
517,518,02-06-2019,2,1,6,0,0,0,1,23.916653,28.31440,54.9167,12.499654,2795,5325,8120
518,519,03-06-2019,2,1,6,0,1,1,1,24.702500,28.75665,49.3333,12.333829,2494,5147,7641
519,520,04-06-2019,2,1,6,0,2,1,1,24.497500,28.91415,48.7083,19.083811,1071,5927,6998
520,521,05-06-2019,2,1,6,0,3,1,2,22.174153,26.29460,61.3333,14.041525,968,6033,7001
521,522,06-06-2019,2,1,6,0,4,1,1,22.720847,27.11460,61.1250,5.167375,1027,6028,7055
522,523,07-06-2019,2,1,6,0,5,1,1,24.702500,28.47210,56.7083,10.542450,1038,6456,7494
523,524,08-06-2019,2,1,6,0,6,0,1,26.615847,29.89310,46.7917,11.750661,1488,6248,7736
524,525,09-06-2019,2,1,6,0,0,0,1,29.144153,32.41835,43.7083,9.667229,2708,4790,7498
525,526,10-06-2019,2,1,6,0,1,1,1,29.793347,33.17585,53.8333,8.959307,2224,4374,6598
526,527,11-06-2019,2,1,6,0,2,1,2,29.554153,32.98605,58.7917,13.916771,1017,5647,6664
527,528,12-06-2019,2,1,6,0,3,1,2,26.786653,29.89375,83.3333,14.374582,477,4495,4972
528,529,13-06-2019,2,1,6,0,4,1,1,26.889153,30.55585,58.2083,22.999693,1173,6248,7421
529,530,14-06-2019,2,1,6,0,5,1,1,26.581653,31.21915,56.9583,17.000111,1180,6183,7363
530,531,15-06-2019,2,1,6,0,6,0,1,26.205847,29.98770,58.9583,11.833339,1563,6102,7665
531,532,16-06-2019,2,1,6,0,0,0,1,25.898347,29.73540,50.4167,11.166689,2963,4739,7702
532,533,17-06-2019,2,1,6,0,1,1,1,24.292500,28.59875,59.8750,9.708568,2634,4344,6978
533,534,18-06-2019,2,1,6,0,2,1,2,23.301653,27.24210,77.7917,11.707982,653,4446,5099
534,535,19-06-2019,2,1,6,0,3,1,1,28.221653,32.73460,69.0000,9.917139,968,5857,6825
535,536,20-06-2019,2,1,6,0,4,1,1,32.082500,36.04875,59.2083,7.625404,872,5339,6211
536,537,21-06-2019,3,1,6,0,5,1,1,33.039153,37.62710,56.7917,7.958729,778,5127,5905
537,538,22-06-2019,3,1,6,0,6,0,1,31.877500,36.20605,57.3750,12.250414,964,4859,5823
538,539,23-06-2019,3,1,6,0,0,0,1,29.998347,32.63960,53.4583,12.041307,2657,4801,7458
539,540,24-06-2019,3,1,6,0,1,1,1,30.476653,33.71270,47.9167,9.750175,2551,4340,6891
540,541,25-06-2019,3,1,6,0,2,1,1,29.349153,32.70210,50.4167,20.125661,1139,5640,6779
541,542,26-06-2019,3,1,6,0,3,1,1,25.864153,29.73520,37.3333,23.292014,1077,6365,7442
542,543,27-06-2019,3,1,6,0,4,1,1,28.597500,32.03960,36.0000,18.208925,1077,6258,7335
543,544,28-06-2019,3,1,6,0,5,1,1,30.715847,33.77560,42.2500,11.500550,921,5958,6879
544,545,29-06-2019,3,1,6,0,6,0,1,34.200847,39.33065,48.8750,11.082939,829,4634,5463
545,546,30-06-2019,3,1,6,0,0,0,1,31.365000,34.37540,60.1250,10.791757,1455,4232,5687
546,547,01-07-2019,3,1,7,0,1,1,1,33.449153,37.53145,51.8750,11.291443,1421,4110,5531
547,548,02-07-2019,3,1,7,0,2,1,1,32.048347,35.10190,44.7083,13.082889,904,5323,6227
548,549,03-07-2019,3,1,7,0,3,1,1,32.014153,35.13250,49.2083,8.457879,1052,5608,6660
549,550,04-07-2019,3,1,7,1,4,0,1,32.355847,36.61685,53.8750,9.041650,2562,4841,7403
550,551,05-07-2019,3,1,7,0,5,1,1,33.927500,38.06835,45.7917,12.999943,1405,4836,6241
551,552,06-07-2019,3,1,7,0,6,0,1,33.961653,37.62665,45.0833,9.791514,1366,4841,6207
552,553,07-07-2019,3,1,7,0,0,0,1,35.328347,40.24565,49.2083,10.958118,1448,3392,4840
553,554,08-07-2019,3,1,7,0,1,1,1,33.722500,39.51980,57.3750,8.417143,1203,3469,4672
554,555,09-07-2019,3,1,7,0,2,1,2,29.144153,32.70270,68.3333,12.125325,998,5571,6569
555,556,10-07-2019,3,1,7,0,3,1,2,29.554153,33.23980,66.7500,10.166379,954,5336,6290
556,557,11-07-2019,3,1,7,0,4,1,1,29.383347,32.51355,63.3333,10.166111,975,6289,7264
557,558,12-07-2019,3,1,7,0,5,1,1,29.349153,32.73415,52.9583,9.833925,1032,6414,7446
558,559,13-07-2019,3,1,7,0,6,0,2,29.998347,33.39665,48.5833,5.416950,1511,5988,7499
559,560,14-07-2019,3,1,7,0,0,0,2,28.836653,33.30210,69.9167,9.626493,2355,4614,6969
560,561,15-07-2019,3,1,7,0,1,1,1,30.579153,35.25980,71.7917,11.166689,1920,4111,6031
561,562,16-07-2019,3,1,7,0,2,1,1,31.296653,36.20625,64.5000,11.000529,1088,5742,6830
562,563,17-07-2019,3,1,7,0,3,1,1,33.551653,37.78415,50.5833,7.666743,921,5865,6786
563,564,18-07-2019,3,1,7,0,4,1,1,32.526653,37.27915,57.7083,9.208614,799,4914,5713
564,565,19-07-2019,3,1,7,0,5,1,1,31.570000,35.73210,60.0417,11.083743,888,5703,6591
565,566,20-07-2019,3,1,7,0,6,0,2,27.299153,30.65125,84.4167,14.000789,747,5123,5870
566,567,21-07-2019,3,1,7,0,0,0,3,24.429153,27.49560,86.5417,14.291100,1264,3195,4459
567,568,22-07-2019,3,1,7,0,1,1,2,27.367500,31.15625,76.2500,6.292694,2544,4866,7410
568,569,23-07-2019,3,1,7,0,2,1,1,30.408347,34.50085,69.4167,9.291761,1135,5831,6966
569,570,24-07-2019,3,1,7,0,3,1,1,30.784153,35.32250,65.5000,14.167418,1140,6452,7592
570,571,25-07-2019,3,1,7,0,4,1,1,29.690847,32.70270,45.0000,11.041600,1383,6790,8173
571,572,26-07-2019,3,1,7,0,5,1,1,31.843347,36.96315,59.6667,19.082471,1036,5825,6861
572,573,27-07-2019,3,1,7,0,6,0,1,32.048347,36.71085,59.4583,10.250464,1259,5645,6904
573,574,28-07-2019,3,1,7,0,0,0,1,30.989153,34.88020,61.3333,10.542450,2234,4451,6685
574,575,29-07-2019,3,1,7,0,1,1,1,29.588347,33.39665,62.3750,11.416532,2153,4444,6597
575,576,30-07-2019,3,1,7,0,2,1,1,29.964153,34.24935,66.8750,10.292339,1040,6065,7105
576,577,31-07-2019,3,1,7,0,3,1,1,29.246653,33.14480,70.4167,11.083475,968,6248,7216
577,578,01-08-2019,3,1,8,0,4,1,1,29.417500,33.36540,67.7500,9.458993,1074,6506,7580
578,579,02-08-2019,3,1,8,0,5,1,1,30.852500,35.35440,65.9583,8.666718,983,6278,7261
579,580,03-08-2019,3,1,8,0,6,0,2,31.399153,36.14335,64.2500,14.458064,1328,5847,7175
580,581,04-08-2019,3,1,8,0,0,0,1,32.526653,37.56335,61.3333,17.249686,2345,4479,6824
581,582,05-08-2019,3,1,8,0,1,1,1,31.535847,36.55395,65.2500,19.458207,1707,3757,5464
582,583,06-08-2019,3,1,8,0,2,1,2,30.852500,35.51230,65.4167,8.666718,1233,5780,7013
583,584,07-08-2019,3,1,8,0,3,1,2,30.169153,34.88105,70.3750,7.832836,1278,5995,7273
584,585,08-08-2019,3,1,8,0,4,1,2,30.750000,35.38585,67.2917,7.416900,1263,6271,7534
585,586,09-08-2019,3,1,8,0,5,1,1,30.989153,34.97540,62.0417,10.458700,1196,6090,7286
586,587,10-08-2019,3,1,8,0,6,0,2,29.349153,33.39710,71.5833,16.000471,1065,4721,5786
587,588,11-08-2019,3,1,8,0,0,0,2,28.392500,31.91335,73.2917,13.834093,2247,4052,6299
588,589,12-08-2019,3,1,8,0,1,1,1,28.734153,32.22895,53.0417,8.208304,2182,4362,6544
589,590,13-08-2019,3,1,8,0,2,1,1,29.554153,33.11270,54.5417,9.126204,1207,5676,6883
590,591,14-08-2019,3,1,8,0,3,1,1,29.793347,33.83895,68.6667,11.333586,1128,5656,6784
591,592,15-08-2019,3,1,8,0,4,1,1,28.973347,32.70185,61.9583,11.374657,1198,6149,7347
592,593,16-08-2019,3,1,8,0,5,1,1,29.485847,32.73440,51.9167,9.500332,1338,6267,7605
593,594,17-08-2019,3,1,8,0,6,0,1,29.656653,12.12000,57.0833,15.500718,1483,5665,7148
594,595,18-08-2019,3,1,8,0,0,0,1,27.811653,30.90355,60.3333,11.917089,2827,5038,7865
595,596,19-08-2019,3,1,8,0,1,1,2,26.069153,30.17770,71.1667,5.792150,1208,3341,4549
596,597,20-08-2019,3,1,8,0,2,1,2,26.069153,29.79835,73.4167,8.708593,1026,5504,6530

In [42]:
###Sample the data 
#shows random data
sub_df=df.sample(20)

In [43]:
sub_df

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
698,699,30-11-2019,4,1,11,0,6,0,1,12.231653,16.19335,64.9583,3.917544,362,5306,5668
562,563,17-07-2019,3,1,7,0,3,1,1,33.551653,37.78415,50.5833,7.666743,921,5865,6786
134,135,15-05-2018,2,0,5,0,2,1,2,23.062500,26.80000,86.7083,10.249593,1582,2971,4553
112,113,23-04-2018,2,0,4,0,1,1,2,18.860000,22.50605,88.7917,15.458575,1462,2574,4036
400,401,05-02-2019,1,1,2,0,2,1,2,10.899153,13.22605,68.7917,11.791732,318,2629,2947
46,47,16-02-2018,1,0,2,0,5,1,1,13.048701,15.81000,42.3478,16.869997,218,1897,2115
446,447,23-03-2019,2,1,3,0,6,0,2,24.668347,28.50335,69.4167,7.792100,2469,5893,8362
407,408,12-02-2019,1,1,2,0,2,1,1,5.227500,5.08290,46.4583,27.417204,73,1456,1529
155,156,05-06-2018,2,0,6,0,2,1,2,26.581653,30.84020,65.2500,9.292364,1685,3221,4906
677,678,09-11-2019,4,1,11,0,6,0,1,14.828347,17.77065,54.0833,14.375386,709,5283,5992
334,335,01-12-2018,4,0,12,0,6,0,1,12.812500,15.27770,52.4583,14.750586,182,3545,3727
412,413,17-02-2019,1,1,2,0,0,0,1,14.076653,17.58145,63.4583,13.791682,349,3805,4154
244,245,02-09-2018,3,0,9,0,0,0,2,26.376653,30.24040,72.7083,9.375243,875,3852,4727
310,311,07-11-2018,4,0,11,0,3,1,1,16.195000,20.04355,75.8750,3.834075,373,3662,4035
592,593,16-08-2019,3,1,8,0,5,1,1,29.485847,32.73440,51.9167,9.500332,1338,6267,7605
362,363,29-12-2018,1,0,12,0,6,0,1,10.181653,13.19460,57.4167,8.000604,254,2169,2423
10,11,11-01-2018,1,0,1,0,4,1,2,6.932731,9.57320,68.6364,8.182844,43,1220,1263
491,492,07-05-2019,2,1,5,0,2,1,2,22.037500,26.35710,66.4167,15.458307,1008,5265,6273
324,325,21-11-2018,4,0,11,0,3,1,3,18.347500,22.25310,91.0000,9.249618,220,2545,2765
666,667,29-10-2019,4,1,10,0,2,1,3,18.040000,21.97000,88.0000,23.999400,2,20,22

In [45]:
#to write the output file
sub_df.to_csv("sample_output.csv")
#to write the output in excel
sub_df.to_excel("sample_out.xlsx")

In [47]:
sub_df=sub_df[["temp","hum","mnth","windspeed"]]

In [48]:
sub_df.shape

(20, 4)

In [49]:
sub_df.head()

          temp      hum  mnth  windspeed
698  12.231653  64.9583    11   3.917544
562  33.551653  50.5833     7   7.666743
134  23.062500  86.7083     5  10.249593
112  18.860000  88.7917     4  15.458575
400  10.899153  68.7917     2  11.791732

In [50]:
#Sorting

In [51]:
sub_df.sort_values("temp")

          temp      hum  mnth  windspeed
407   5.227500  46.4583     2  27.417204
10    6.932731  68.6364     1   8.182844
362  10.181653  57.4167    12   8.000604
400  10.899153  68.7917     2  11.791732
698  12.231653  64.9583    11   3.917544
334  12.812500  52.4583    12  14.750586
46   13.048701  42.3478     2  16.869997
412  14.076653  63.4583     2  13.791682
677  14.828347  54.0833    11  14.375386
310  16.195000  75.8750    11   3.834075
666  18.040000  88.0000    10  23.999400
324  18.347500  91.0000    11   9.249618
112  18.860000  88.7917     4  15.458575
491  22.037500  66.4167     5  15.458307
134  23.062500  86.7083     5  10.249593
446  24.668347  69.4167     3   7.792100
244  26.376653  72.7083     9   9.375243
155  26.581653  65.2500     6   9.292364
592  29.485847  51.9167     8   9.500332
562  33.551653  50.5833     7   7.666743

In [52]:
sub_df.sort_values("temp", ascending=False)

          temp      hum  mnth  windspeed
562  33.551653  50.5833     7   7.666743
592  29.485847  51.9167     8   9.500332
155  26.581653  65.2500     6   9.292364
244  26.376653  72.7083     9   9.375243
446  24.668347  69.4167     3   7.792100
134  23.062500  86.7083     5  10.249593
491  22.037500  66.4167     5  15.458307
112  18.860000  88.7917     4  15.458575
324  18.347500  91.0000    11   9.249618
666  18.040000  88.0000    10  23.999400
310  16.195000  75.8750    11   3.834075
677  14.828347  54.0833    11  14.375386
412  14.076653  63.4583     2  13.791682
46   13.048701  42.3478     2  16.869997
334  12.812500  52.4583    12  14.750586
698  12.231653  64.9583    11   3.917544
400  10.899153  68.7917     2  11.791732
362  10.181653  57.4167    12   8.000604
10    6.932731  68.6364     1   8.182844
407   5.227500  46.4583     2  27.417204

In [53]:
sub_df.sort_values(["mnth","temp"],ascending=[True,False])

          temp      hum  mnth  windspeed
10    6.932731  68.6364     1   8.182844
412  14.076653  63.4583     2  13.791682
46   13.048701  42.3478     2  16.869997
400  10.899153  68.7917     2  11.791732
407   5.227500  46.4583     2  27.417204
446  24.668347  69.4167     3   7.792100
112  18.860000  88.7917     4  15.458575
134  23.062500  86.7083     5  10.249593
491  22.037500  66.4167     5  15.458307
155  26.581653  65.2500     6   9.292364
562  33.551653  50.5833     7   7.666743
592  29.485847  51.9167     8   9.500332
244  26.376653  72.7083     9   9.375243
666  18.040000  88.0000    10  23.999400
324  18.347500  91.0000    11   9.249618
310  16.195000  75.8750    11   3.834075
677  14.828347  54.0833    11  14.375386
698  12.231653  64.9583    11   3.917544
334  12.812500  52.4583    12  14.750586
362  10.181653  57.4167    12   8.000604

In [56]:
#Group By
#it is used to see aggregated result on the dataframe
for i in range(1,13):
    print(i, round(df[df["mnth"]==i]["temp"].mean(),2))

1 9.69
2 12.24
3 16.01
4 19.27
5 24.39
6 28.05
7 30.97
8 29.05
9 25.28
10 19.89
11 15.14
12 13.29

In [57]:
df.groupby("mnth")["temp"].mean()
#mnth: Group column
#temp: Aggregating Column
#mean: Aggregating function

mnth
1      9.694201
2     12.235249
3     16.012089
4     19.269952
5     24.386735
6     28.047985
7     30.974287
8     29.051844
9     25.275884
10    19.885500
11    15.138010
12    13.285270
Name: temp, dtype: float64

In [58]:
df.groupby("mnth")[["temp","hum"]].mean()

           temp        hum
mnth
1      9.694201  58.582827
2     12.235249  56.322686
3     16.012089  58.847503
4     19.269952  58.806312
5     24.386735  68.895831
6     28.047985  57.580552
7     30.974287  59.787632
8     29.051844  63.773010
9     25.275884  71.471437
10    19.885500  69.376087
11    15.138010  62.487648
12    13.285270  66.604052

In [59]:
df.groupby("mnth")[["temp","hum"]].median()

           temp       hum
mnth
1      8.917500  53.76630
2     11.706525  53.79170
3     15.594124  58.02080
4     18.842923  56.95835
5     24.429153  70.72920
6     28.307077  57.79165
7     30.698750  59.56250
8     29.015536  63.91665
9     25.471250  71.08335
10    20.124173  70.25000
11    14.725847  61.70835
12    12.846673  64.02085

In [72]:
d={"hum":["max","min","mean"],"temp":["median","std"],"windspeed":["count"]}
df.groupby("mnth").agg(d)

          hum                           temp           windspeed
          max      min       mean     median       std     count
mnth
1     91.1250  31.1250  58.582827   8.917500  3.413911        62
2     92.9167  18.7917  56.322686  11.706525  3.479087        56
3     94.8261   0.0000  58.847503  15.594124  4.291649        62
4     88.8333  25.4167  58.806312  18.842923  3.577446        60
5     92.2500  36.0417  68.895831  24.429153  2.992979        62
6     83.3333  30.5000  57.580552  28.307077  2.709868        60
7     86.5417  39.6250  59.787632  30.698750  2.129953        62
8     85.0000  41.5000  63.773010  29.015536  1.636442        62
9     97.2500  46.7083  71.471437  25.471250  2.538568        60
10    90.6250  46.3333  69.376087  20.124173  3.444389        62
11    96.2500  33.3478  62.487648  14.725847  2.645619        60
12    97.0417  44.1250  66.604052  12.846673  2.781923        62

In [74]:
df.head()

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,01-01-2018,1,0,1,0,1,1,2,14.110847,18.18125,80.5833,10.749882,331,654,985
1,2,02-01-2018,1,0,1,0,2,1,2,14.902598,17.68695,69.6087,16.652113,131,670,801
2,3,03-01-2018,1,0,1,0,3,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349
3,4,04-01-2018,1,0,1,0,4,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562
4,5,05-01-2018,1,0,1,0,5,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600

In [75]:
df.loc[2:5]

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
2,3,03-01-2018,1,0,1,0,3,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349
3,4,04-01-2018,1,0,1,0,4,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562
4,5,05-01-2018,1,0,1,0,5,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600
5,6,06-01-2018,1,0,1,0,6,0,1,8.378268,11.66045,51.8261,6.000868,88,1518,1606

In [80]:
df=df.set_index("dteday")

In [81]:
df.head()

,instant,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
dteday,,,,,,,,,,,,,,,
01-01-2018,1,1,0,1,0,1,1,2,14.110847,18.18125,80.5833,10.749882,331,654,985
02-01-2018,2,1,0,1,0,2,1,2,14.902598,17.68695,69.6087,16.652113,131,670,801
03-01-2018,3,1,0,1,0,3,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349
04-01-2018,4,1,0,1,0,4,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562
05-01-2018,5,1,0,1,0,5,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600

In [82]:
df.iloc[2:5]

,instant,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
dteday,,,,,,,,,,,,,,,
03-01-2018,3,1,0,1,0,3,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349
04-01-2018,4,1,0,1,0,4,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562
05-01-2018,5,1,0,1,0,5,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600

In [83]:
df.loc[df["temp"].idxmin()]

instant        22.000000
season          1.000000
yr              0.000000
mnth            1.000000
holiday         0.000000
weekday         1.000000
workingday      1.000000
weathersit      1.000000
temp            2.424346
atemp           3.953480
hum            40.000000
windspeed      11.521990
casual         93.000000
registered    888.000000
cnt           981.000000
Name: 22-01-2018, dtype: float64

In [84]:
df.isna().any()

instant       False
season        False
yr            False
mnth          False
holiday       False
weekday       False
workingday    False
weathersit    False
temp          False
atemp         False
hum           False
windspeed     False
casual        False
registered    False
cnt           False
dtype: bool